### ISSUE TITLE
'lein uberjar' returned a non-zero code: 1

### ISSUE THREAD

**Issue by saintx** [threatgrid/ctia#213]
Exception in thread "main" java.lang.ClassNotFoundException: ctia.Hook, compiling:(ctia/flows/autoload.clj:28:7)
	...
Caused by: java.lang.ClassNotFoundException: ctia.Hook
	... many many more
Compilation failed: Subprocess failed
The command '/bin/sh -c lein uberjar' returned a non-zero code: 1

**Comment by saintx** [comment]
Step 7 : RUN lein uberjar
     ---> Running in 28f56cdfc952
    Retrieving org/clojure/test.check/0.7.0/test.check-0.7.0.jar from central
    Compiling ctia.main
    java.lang.ClassNotFoundException: ctia.Hook, compiling:(ctia/flows/autoload.clj:28:7)
    Exception in thread "main" java.lang.ClassNotFoundException: ctia.Hook, compiling:(ctia/flows/autoload.clj:28:7)
      at clojure.lang.Compiler.analyze(Compiler.java:6543)
      at clojure.lang.Compiler.analyze(Compiler.java:6485)
      at clojure.lang.Compiler$InvokeExpr.parse(Compiler.java:3740)
      at clojure.lang.Compiler.analyzeSeq(Compiler.java:6725)
      at clojure.lang.Compiler.analyze(Compiler.java:6524)
      at clojure.lang.Compiler.analyze(Compiler.java:6485)
      at clojure.lang.Compiler$IfExpr$Parser.parse(Compiler.java:2772)
      at clojure.lang.Compiler.analyzeSeq(Compiler.java:6723)
      at clojure.lang.Compiler.analyze(Compiler.java:6524)
      at clojure.lang.Compiler.analyzeSeq(Compiler.java:6711)
      at clojure.lang.Compiler.analyze(Compiler.java:6524)
      at clojure.lang.Compiler.analyze(Compiler.java:6485)
      at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:5861)
      at clojure.lang.Compiler$LetExpr$Parser.parse(Compiler.java:6179)
      at clojure.lang.Compiler.analyzeSeq(Compiler.java:6723)
      at clojure.lang.Compiler.analyze(Compiler.java:6524)
      at clojure.lang.Compiler.analyzeSeq(Compiler.java:6711)
      at clojure.lang.Compiler.analyze(Compiler.java:6524)
      at clojure.lang.Compiler.analyze(Compiler.java:6485)
      at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:5861)
      at clojure.lang.Compiler$FnMethod.parse(Compiler.java:5296)
      at clojure.lang.Compiler$FnExpr.parse(Compiler.java:3925)
      at clojure.lang.Compiler.analyzeSeq(Compiler.java:6721)
      at clojure.lang.Compiler.analyze(Compiler.java:6524)
      at clojure.lang.Compiler.analyzeSeq(Compiler.java:6711)
      at clojure.lang.Compiler.analyze(Compiler.java:6524)
      at clojure.lang.Compiler.access$300(Compiler.java:38)
      at clojure.lang.Compiler$DefExpr$Parser.parse(Compiler.java:577)
      at clojure.lang.Compiler.analyzeSeq(Compiler.java:6723)
      at clojure.lang.Compiler.analyze(Compiler.java:6524)
      at clojure.lang.Compiler.analyze(Compiler.java:6485)
      at clojure.lang.Compiler.compile1(Compiler.java:7318)
      at clojure.lang.Compiler.compile(Compiler.java:7390)
      at clojure.lang.RT.compile(RT.java:399)
      at clojure.lang.RT.load(RT.java:444)
      at clojure.lang.RT.load(RT.java:412)
      at clojure.core$load$fn__5448.invoke(core.clj:5866)
      at clojure.core$load.doInvoke(core.clj:5865)
      at clojure.lang.RestFn.invoke(RestFn.java:408)
      at clojure.core$load_one.invoke(core.clj:5671)
      at clojure.core$load_lib$fn__5397.invoke(core.clj:5711)
      at clojure.core$load_lib.doInvoke(core.clj:5710)
      at clojure.lang.RestFn.applyTo(RestFn.java:142)
      at clojure.core$apply.invoke(core.clj:632)
      at clojure.core$load_libs.doInvoke(core.clj:5749)
      at clojure.lang.RestFn.applyTo(RestFn.java:137)
      at clojure.core$apply.invoke(core.clj:632)
      at clojure.core$require.doInvoke(core.clj:5832)
      at clojure.lang.RestFn.invoke(RestFn.java:3204)
      at ctia.init$loading__5340__auto____38.invoke(init.clj:1)
      at clojure.lang.AFn.applyToHelper(AFn.java:152)
      at clojure.lang.AFn.applyTo(AFn.java:144)
      at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3623)
      at clojure.lang.Compiler.compile1(Compiler.java:7323)
      at clojure.lang.Compiler.compile1(Compiler.java:7313)
      at clojure.lang.Compiler.compile(Compiler.java:7390)
      at clojure.lang.RT.compile(RT.java:399)
      at clojure.lang.RT.load(RT.java:444)
      at clojure.lang.RT.load(RT.java:412)
      at clojure.core$load$fn__5448.invoke(core.clj:5866)
      at clojure.core$load.doInvoke(core.clj:5865)
      at clojure.lang.RestFn.invoke(RestFn.java:408)
      at clojure.core$load_one.invoke(core.clj:5671)
      at clojure.core$load_lib$fn__5397.invoke(core.clj:5711)
      at clojure.core$load_lib.doInvoke(core.clj:5710)
      at clojure.lang.RestFn.applyTo(RestFn.java:142)
      at clojure.core$apply.invoke(core.clj:632)
      at clojure.core$load_libs.doInvoke(core.clj:5749)
      at clojure.lang.RestFn.applyTo(RestFn.java:137)
      at clojure.core$apply.invoke(core.clj:632)
      at clojure.core$require.doInvoke(core.clj:5832)
      at clojure.lang.RestFn.invoke(RestFn.java:408)
      at ctia.main$loading__5340__auto____36.invoke(main.clj:1)
      at clojure.lang.AFn.applyToHelper(AFn.java:152)
      at clojure.lang.AFn.applyTo(AFn.java:144)
      at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3623)
      at clojure.lang.Compiler.compile1(Compiler.java:7323)
      at clojure.lang.Compiler.compile1(Compiler.java:7313)
      at clojure.lang.Compiler.compile(Compiler.java:7390)
      at clojure.lang.RT.compile(RT.java:399)
      at clojure.lang.RT.load(RT.java:444)
      at clojure.lang.RT.load(RT.java:412)
      at clojure.core$load$fn__5448.invoke(core.clj:5866)
      at clojure.core$load.doInvoke(core.clj:5865)
      at clojure.lang.RestFn.invoke(RestFn.java:408)
      at clojure.core$load_one.invoke(core.clj:5671)
      at clojure.core$compile$fn__5453.invoke(core.clj:5877)
      at clojure.core$compile.invoke(core.clj:5876)
      at user$eval20$fn__29.invoke(form-init7114887845113430397.clj:1)
      at user$eval20.invoke(form-init7114887845113430397.clj:1)
      at clojure.lang.Compiler.eval(Compiler.java:6782)
      at clojure.lang.Compiler.eval(Compiler.java:6772)
      at clojure.lang.Compiler.eval(Compiler.java:6772)
      at clojure.lang.Compiler.load(Compiler.java:7227)
      at clojure.lang.Compiler.loadFile(Compiler.java:7165)
      at clojure.main$load_script.invoke(main.clj:275)
      at clojure.main$init_opt.invoke(main.clj:280)
      at clojure.main$initialize.invoke(main.clj:308)
      at clojure.main$null_opt.invoke(main.clj:343)
      at clojure.main$main.doInvoke(main.clj:421)
      at clojure.lang.RestFn.invoke(RestFn.java:421)
      at clojure.lang.Var.invoke(Var.java:383)
      at clojure.lang.AFn.applyToHelper(AFn.java:156)
      at clojure.lang.Var.applyTo(Var.java:700)
      at clojure.main.main(main.java:37)
    Caused by: java.lang.ClassNotFoundException: ctia.Hook
      at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
      at clojure.lang.DynamicClassLoader.findClass(DynamicClassLoader.java:69)
      at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
      at clojure.lang.DynamicClassLoader.loadClass(DynamicClassLoader.java:77)
      at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
      at java.lang.Class.forName0(Native Method)
      at java.lang.Class.forName(Class.java:348)
      at clojure.lang.RT.classForName(RT.java:2154)
      at clojure.lang.RT.classForName(RT.java:2163)
      at clojure.lang.Compiler.resolveIn(Compiler.java:7000)
      at clojure.lang.Compiler.resolve(Compiler.java:6963)
      at clojure.lang.Compiler.analyzeSymbol(Compiler.java:6924)
      at clojure.lang.Compiler.analyze(Compiler.java:6506)
      ... 104 more
    Compilation failed: Subprocess failed
    The command '/bin/sh -c lein uberjar' returned a non-zero code: 1

**Comment by polygloton** [comment]
Can this be closed?
