### ISSUE TITLE
Make sure we are logging stacktraces

### ISSUE THREAD

**Issue by polygloton** [threatgrid/ctia#381]
In cita.http.exceptions, it doesn't seem like we are logging stacktraces.

See https://github.com/threatgrid/threatbrain/blob/master/src/threatbrain/lib/utils.clj#L8

**Comment by gbuisson** [comment]
Just tried and we are logging stacktraces, here is a sample for a schema validation error:
```clojure
2016-11-22 14:44:53,752 ERROR (qtp1194931013-26 - /ctia/campaign) [ctia.http.exceptions] - Request validation failed: {:descrissption disallowed-key} - Meta: #schema.utils.ErrorContainer{:error {:descrissption disallowed-key}, :type :compojure.api.exception/request-validation}
clojure.lang.ExceptionInfo: Request validation failed: {:descrissption disallowed-key} schema.utils.ErrorContainer@7968c15a
	at clojure.core$ex_info.invokeStatic(core.clj:4617)
	at clojure.core$ex_info.invoke(core.clj:4617)
	at compojure.api.coerce$coerce_BANG_.invokeStatic(coerce.clj:61)
	at compojure.api.coerce$coerce_BANG_.invoke(coerce.clj:53)
	at ctia.http.routes.campaign$fn__40122$fn__40124.invoke(campaign.clj:20)
	at compojure.core$make_route$fn__36925.invoke(core.clj:135)
	at compojure.core$pre_init$fn__36964.invoke(core.clj:268)
	at compojure.api.coerce$body_coercer_middleware$fn__38212.invoke(coerce.clj:51)
	at compojure.core$pre_init$fn__36966$fn__36967.invoke(core.clj:271)
	at compojure.core$wrap_route_middleware$fn__36918.invoke(core.clj:121)
	at compojure.core$wrap_route_info$fn__36922.invoke(core.clj:126)
	at compojure.core$if_route$fn__36880.invoke(core.clj:45)
	at compojure.core$if_method$fn__36870.invoke(core.clj:27)
	at compojure.core$wrap_routes$fn__36972.invoke(core.clj:279)
	at compojure.api.routes.Route.invoke(routes.clj:74)
	at compojure.core$routing$fn__36932.invoke(core.clj:151)
	at clojure.core$some.invokeStatic(core.clj:2592)
	at clojure.core$some.invoke(core.clj:2583)
	at compojure.core$routing.invokeStatic(core.clj:151)
	at compojure.core$routing.doInvoke(core.clj:148)
	at clojure.lang.RestFn.applyTo(RestFn.java:139)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$apply.invoke(core.clj:641)
	at compojure.core$routes$fn__36936.invoke(core.clj:156)
	at compojure.core$routing$fn__36932.invoke(core.clj:151)
	at clojure.core$some.invokeStatic(core.clj:2592)
	at clojure.core$some.invoke(core.clj:2583)
	at compojure.core$routing.invokeStatic(core.clj:151)
	at compojure.core$routing.doInvoke(core.clj:148)
	at clojure.lang.RestFn.invoke(RestFn.java:423)
	at ctia.http.routes.campaign$fn__40122.invokeStatic(campaign.clj:18)
	at ctia.http.routes.campaign$fn__40122.invoke(campaign.clj:18)
	at compojure.core$if_context$fn__36954.invoke(core.clj:220)
	at compojure.api.routes.Route.invoke(routes.clj:74)
	at compojure.api.core$handle$fn__38349.invoke(core.clj:8)
	at clojure.core$some.invokeStatic(core.clj:2592)
	at clojure.core$some.invoke(core.clj:2583)
	at compojure.api.core$handle.invokeStatic(core.clj:8)
```

**Comment by polygloton** [comment]
Nice, thanks!
