### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by sashank** [threatgrid/ctia#402]
i am using os xi EI Capitan (10.11.6) 

I forked the ctia project , did `brew install leiningen` and did `lein run`.
 I get the below error after a while and hangs , is there any additional step that needs to be done ? 

```
Exception in thread "main" java.net.ConnectException: Connection refused, compiling:(/private/var/folders/4p/1w361z0n52b4c3ypmcl3_w_80000gn/T/form-init5505121091341658859.clj:1:125)
	at clojure.lang.Compiler.load(Compiler.java:7391)
	at clojure.lang.Compiler.loadFile(Compiler.java:7317)
	at clojure.main$load_script.invokeStatic(main.clj:275)
	at clojure.main$init_opt.invokeStatic(main.clj:277)
	at clojure.main$init_opt.invoke(main.clj:277)
	at clojure.main$initialize.invokeStatic(main.clj:308)
	at clojure.main$null_opt.invokeStatic(main.clj:342)
	at clojure.main$null_opt.invoke(main.clj:339)
	at clojure.main$main.invokeStatic(main.clj:421)
	at clojure.main$main.doInvoke(main.clj:384)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:117)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:177)
	at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:304)
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:611)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:446)
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:882)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
	at clj_http.core$request.invokeStatic(core.clj:298)
	at clj_http.core$request.invoke(core.clj:208)
	at clojure.lang.Var.invoke(Var.java:379)
	at clj_http.client$wrap_request_timing$fn__23358.invoke(client.clj:801)
	at clj_http.headers$wrap_header_map$fn__22566.invoke(headers.clj:143)
	at clj_http.client$wrap_query_params$fn__23274.invoke(client.clj:624)
	at clj_http.client$wrap_basic_auth$fn__23281.invoke(client.clj:640)
	at clj_http.client$wrap_oauth$fn__23285.invoke(client.clj:650)
	at clj_http.client$wrap_user_info$fn__23290.invoke(client.clj:663)
	at clj_http.client$wrap_url$fn__23344.invoke(client.clj:767)
	at clj_http.client$wrap_redirects$fn__23102.invoke(client.clj:237)
	at clj_http.client$wrap_decompression$fn__23121.invoke(client.clj:309)
	at clj_http.client$wrap_input_coercion$fn__23213.invoke(client.clj:488)
	at clj_http.client$wrap_additional_header_parsing$fn__23234.invoke(client.clj:522)
	at clj_http.client$wrap_output_coercion$fn__23204.invoke(client.clj:438)
	at clj_http.client$wrap_exceptions$fn__23088.invoke(client.clj:189)
	at clj_http.client$wrap_accept$fn__23248.invoke(client.clj:562)
	at clj_http.client$wrap_accept_encoding$fn__23254.invoke(client.clj:579)
	at clj_http.client$wrap_content_type$fn__23243.invoke(client.clj:555)
	at clj_http.client$wrap_form_params$fn__23325.invoke(client.clj:726)
	at clj_http.client$wrap_nested_params$fn__23339.invoke(client.clj:756)
	at clj_http.client$wrap_method$fn__23295.invoke(client.clj:670)
	at clj_http.cookies$wrap_cookies$fn__22495.invoke(cookies.clj:124)
	at clj_http.links$wrap_links$fn__22751.invoke(links.clj:51)
	at clj_http.client$wrap_unknown_host$fn__23348.invoke(client.clj:776)
	at clj_http.client$head.invokeStatic(client.clj:885)
	at clj_http.client$head.doInvoke(client.clj:881)
	at clojure.lang.RestFn.invoke(RestFn.java:423)
	at clojurewerkz.elastisch.rest$head.invokeStatic(rest.clj:102)
	at clojurewerkz.elastisch.rest$head.invoke(rest.clj:100)
	at clojurewerkz.elastisch.rest.index$exists_QMARK_.invokeStatic(index.clj:65)
	at clojurewerkz.elastisch.rest.index$exists_QMARK_.invoke(index.clj:60)
	at ctia.lib.es.index$create_BANG_.invokeStatic(index.clj:68)
	at ctia.lib.es.index$create_BANG_.invoke(index.clj:65)
	at ctia.stores.es.store$fn__41352$init_BANG___41357$fn__41358.invoke(store.clj:46)
	at ctia.stores.es.store$fn__41352$init_BANG___41357.invoke(store.clj:41)
	at ctia.init$es_builder__41582.invokeStatic(init.clj:49)
	at ctia.init$es_builder__41582.invoke(init.clj:48)
	at ctia.init$init_store_service_BANG_$fn__41616.invoke(init.clj:120)
	at clojure.core$map$fn__4785.invoke(core.clj:2644)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.RT.seq(RT.java:521)
	at clojure.core$seq__4357.invokeStatic(core.clj:137)
	at clojure.core$dorun.invokeStatic(core.clj:3024)
	at clojure.core$doall.invokeStatic(core.clj:3039)
	at clojure.core$doall.invoke(core.clj:3039)
	at ctia.init$init_store_service_BANG_.invokeStatic(init.clj:119)
	at ctia.init$init_store_service_BANG_.invoke(init.clj:99)
	at ctia.init$start_ctia_BANG_.invokeStatic(init.clj:160)
	at ctia.init$start_ctia_BANG_.doInvoke(init.clj:132)
	at clojure.lang.RestFn.invoke(RestFn.java:457)
	at ctia.main$_main.invokeStatic(main.clj:8)
	at ctia.main$_main.doInvoke(main.clj:5)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.Var.invoke(Var.java:375)
	at user$eval5.invokeStatic(form-init5505121091341658859.clj:1)
	at user$eval5.invoke(form-init5505121091341658859.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6927)
	at clojure.lang.Compiler.eval(Compiler.java:6917)
	at clojure.lang.Compiler.load(Compiler.java:7379)
	... 14 more

```

**Comment by gbuisson** [comment]
Did you setup your docker development environment?
If not then follow this guide: https://github.com/threatgrid/ctia#development

then you need to setup your properties using: https://github.com/threatgrid/ctia/blob/master/scripts/init-properties-for-docker.sh

**Comment by sashank** [comment]
Thanks , it is working now . It was not clear from the instructions what needs to be run first and what later.
