### ISSUE TITLE
Bundle imports creating duplicate documents in ES

### ISSUE THREAD

**Issue by saintx** [threatgrid/ctia#643]
Repeatedly posting the same bundle to my local `/ctia/bundle/import` API endpoint is causing duplicate entities to be created in ES.

The `bundle` object has the exact same information in it each time I import it.  Identical transient IDs,  timestamps, and external IDs.  The documents created in ElasticSearch are identical in every way, *except* for their `:modified_time`.

My understanding is that repeatedly importing the same object should not create duplicates.  Is there an additional configuration step required to prevent my local instance of CTIA from creating duplicate entries?

**Comment by saintx** [comment]
Testing this further, I added my prefix to the "dev-resources/ctia.properties", like so:

```
ctia.store.external-key-prefixes=cisco-,ctia-,hydrant-
```

And confirmed that the new value was loaded when I cleared all of the ElasticSearch data and restarted the CTIA server:

```
 :external-key-prefixes "cisco-,ctia-,hydrant-",
```

However, upon trying to import a bundle, I now get a NullPointerException:

```
2018-01-30 22:14:45,339 ERROR (qtp2053950534-25 - /ctia/bundle/import) [ctia.http.exceptions] -
java.lang.NullPointerException
	at clojure.string$lower_case.invokeStatic(string.clj:217)
	at clojure.string$lower_case.invoke(string.clj:213)
	at ctia.stores.es.query$find_restriction_query_part.invokeStatic(query.clj:10)
	at ctia.stores.es.query$find_restriction_query_part.invoke(query.clj:7)
	at ctia.stores.es.crud$handle_find$fn54747__54760$fn__54761.invoke(crud.clj:193)
	at ctia.stores.es.crud$handle_find$fn54747__54760.invoke(crud.clj:184)
	at clojure.lang.AFn.applyToHelper(AFn.java:165)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.lang.AFunction$1.doInvoke(AFunction.java:29)
	at clojure.lang.RestFn.invoke(RestFn.java:457)
	at ctia.stores.es.store.AttackPatternStore.list_attack_patterns(store.clj:239)
	at ctia.store$fn__4873$G__4869__4878.invoke(store.clj:86)
	at ctia.store$fn__4873$G__4868__4884.invoke(store.clj:86)
	at clojure.lang.AFn.applyToHelper(AFn.java:165)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$apply.invoke(core.clj:652)
	at ctia.store$read_store.invokeStatic(store.clj:145)
	at ctia.store$read_store.doInvoke(store.clj:144)
	at clojure.lang.RestFn.invoke(RestFn.java:490)
	at ctia.http.routes.bundle$find_by_external_ids.invokeStatic(bundle.clj:122)
	at ctia.http.routes.bundle$find_by_external_ids.invoke(bundle.clj:115)
	at ctia.http.routes.bundle$fn__49443$with_existing_entities__49448$fn__49449.invoke(bundle.clj:213)
	at ctia.http.routes.bundle$fn__49443$with_existing_entities__49448.invoke(bundle.clj:209)
	at ctia.http.routes.bundle$fn__49472$prepare_import__49477$fn__49478$fn__49479.invoke(bundle.clj:235)
	at ctia.http.routes.bundle$map_kv$fn__49368.invoke(bundle.clj:165)
	at clojure.core$map$fn__5587.invoke(core.clj:2747)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.RT.seq(RT.java:528)
	at clojure.core$seq__5124.invokeStatic(core.clj:137)
	at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:24)
	at clojure.core.protocols$fn__7835.invokeStatic(protocols.clj:75)
	at clojure.core.protocols$fn__7835.invoke(protocols.clj:75)
	at clojure.core.protocols$fn__7781$G__7776__7794.invoke(protocols.clj:13)
	at clojure.core$reduce.invokeStatic(core.clj:6748)
	at clojure.core$into.invokeStatic(core.clj:6815)
	at clojure.core$into.invoke(core.clj:6807)
	at ctia.http.routes.bundle$map_kv.invokeStatic(bundle.clj:163)
	at ctia.http.routes.bundle$map_kv.invoke(bundle.clj:159)
	at ctia.http.routes.bundle$fn__49472$prepare_import__49477$fn__49478.invoke(bundle.clj:231)
	at ctia.http.routes.bundle$fn__49472$prepare_import__49477.invoke(bundle.clj:224)
	at ctia.http.routes.bundle$fn__49590$import_bundle__49595$fn__49596.invoke(bundle.clj:287)
	at ctia.http.routes.bundle$fn__49590$import_bundle__49595.invoke(bundle.clj:282)
	at ctia.http.routes.bundle$fn__49622$fn__49625.invoke(bundle.clj:332)
	at compojure.core$wrap_response$fn__45005.invoke(core.clj:158)
	at compojure.core$pre_init$fn__45056.invoke(core.clj:328)
	at compojure.api.coerce$body_coercer_middleware$fn__46584.invoke(coerce.clj:51)
	at compojure.core$pre_init$fn__45058$fn__45061.invoke(core.clj:335)
	at compojure.core$wrap_route_middleware$fn__44989.invoke(core.clj:127)
	at compojure.core$wrap_route_info$fn__44994.invoke(core.clj:137)
	at compojure.core$wrap_route_matches$fn__44998.invoke(core.clj:146)
	at compojure.core$wrap_routes$fn__45068.invoke(core.clj:348)
	at compojure.api.routes.Route.invoke(routes.clj:74)
	at compojure.core$routing$fn__45013.invoke(core.clj:185)
	at clojure.core$some.invokeStatic(core.clj:2693)
	at clojure.core$some.invoke(core.clj:2684)
	at compojure.core$routing.invokeStatic(core.clj:185)
	at compojure.core$routing.doInvoke(core.clj:182)
	at clojure.lang.RestFn.applyTo(RestFn.java:139)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$apply.invoke(core.clj:652)
	at compojure.core$routes$fn__45017.invoke(core.clj:192)
	at compojure.core$routing$fn__45013.invoke(core.clj:185)
	at clojure.core$some.invokeStatic(core.clj:2693)
	at clojure.core$some.invoke(core.clj:2684)
	at compojure.core$routing.invokeStatic(core.clj:185)
	at compojure.core$routing.doInvoke(core.clj:182)
	at clojure.lang.RestFn.applyTo(RestFn.java:139)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$apply.invoke(core.clj:652)
	at compojure.core$routes$fn__45017.invoke(core.clj:192)
	at compojure.core$make_context$handler__45045.invoke(core.clj:285)
	at compojure.core$make_context$fn__45047.invoke(core.clj:293)
	at compojure.api.routes.Route.invoke(routes.clj:74)
	at compojure.api.core$handle$fn__46737.invoke(core.clj:8)
	at clojure.core$some.invokeStatic(core.clj:2693)
	at clojure.core$some.invoke(core.clj:2684)
	at compojure.api.core$handle.invokeStatic(core.clj:8)
	at compojure.api.core$handle.invoke(core.clj:7)
	at clojure.core$partial$fn__5561.invoke(core.clj:2616)
	at compojure.api.routes.Route.invoke(routes.clj:74)
	at compojure.core$routing$fn__45013.invoke(core.clj:185)
	at clojure.core$some.invokeStatic(core.clj:2693)
	at clojure.core$some.invoke(core.clj:2684)
	at compojure.core$routing.invokeStatic(core.clj:185)
	at compojure.core$routing.doInvoke(core.clj:182)
	at clojure.lang.RestFn.applyTo(RestFn.java:139)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$apply.invoke(core.clj:652)
	at compojure.core$routes$fn__45017.invoke(core.clj:192)
	at compojure.core$routing$fn__45013.invoke(core.clj:185)
	at clojure.core$some.invokeStatic(core.clj:2693)
	at clojure.core$some.invoke(core.clj:2684)
	at compojure.core$routing.invokeStatic(core.clj:185)
	at compojure.core$routing.doInvoke(core.clj:182)
	at clojure.lang.RestFn.applyTo(RestFn.java:139)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$apply.invoke(core.clj:652)
	at compojure.core$routes$fn__45017.invoke(core.clj:192)
	at compojure.core$make_context$handler__45045.invoke(core.clj:285)
	at compojure.core$make_context$fn__45047.invoke(core.clj:293)
	at compojure.api.routes.Route.invoke(routes.clj:74)
	at compojure.api.core$handle$fn__46737.invoke(core.clj:8)
	at clojure.core$some.invokeStatic(core.clj:2693)
	at clojure.core$some.invoke(core.clj:2684)
	at compojure.api.core$handle.invokeStatic(core.clj:8)
	at compojure.api.core$handle.invoke(core.clj:7)
	at clojure.core$partial$fn__5561.invoke(core.clj:2616)
	at compojure.api.routes.Route.invoke(routes.clj:74)
	at metrics.ring.instrument$handle_request$fn__44392.invoke(instrument.clj:65)
	at metrics.ring.instrument.proxy$java.lang.Object$Callable$7da976d4.call(Unknown Source)
	at com.codahale.metrics.Timer.time(Timer.java:101)
	at metrics.ring.instrument$handle_request.invokeStatic(instrument.clj:64)
	at metrics.ring.instrument$handle_request.invoke(instrument.clj:54)
	at metrics.ring.instrument$instrument$fn__44400.invoke(instrument.clj:91)
	at clj_momo.ring.middleware.metrics$gen_metrics_for$fn__44462$fn__44463.invoke(metrics.clj:59)
	at clj_momo.ring.middleware.metrics.proxy$java.lang.Object$Callable$7da976d4.call(Unknown Source)
	at com.codahale.metrics.Timer.time(Timer.java:101)
	at clj_momo.ring.middleware.metrics$gen_metrics_for$fn__44462.invoke(metrics.clj:59)
	at ctia.http.middleware.cache_control$wrap_cache_control$fn__47779.invoke(cache_control.clj:30)
	at ring.middleware.not_modified$wrap_not_modified$fn__46795.invoke(not_modified.clj:53)
	at compojure.api.routes.Route.invoke(routes.clj:74)
	at compojure.api.core$handle$fn__46737.invoke(core.clj:8)
	at clojure.core$some.invokeStatic(core.clj:2693)
	at clojure.core$some.invoke(core.clj:2684)
	at compojure.api.core$handle.invokeStatic(core.clj:8)
	at compojure.api.core$handle.invoke(core.clj:7)
	at clojure.core$partial$fn__5561.invoke(core.clj:2616)
	at compojure.api.routes.Route.invoke(routes.clj:74)
	at ring.swagger.middleware$wrap_swagger_data$fn__46270.invoke(middleware.clj:35)
	at ring.middleware.http_response$wrap_http_response$fn__46121.invoke(http_response.clj:19)
	at ring.swagger.middleware$wrap_swagger_data$fn__46270.invoke(middleware.clj:35)
	at compojure.api.middleware$wrap_options$fn__46331.invoke(middleware.clj:74)
	at ring.middleware.format_params$wrap_format_params$fn__45854.invoke(format_params.clj:119)
	at ring.middleware.format_params$wrap_format_params$fn__45854.invoke(format_params.clj:119)
	at ring.middleware.format_params$wrap_format_params$fn__45854.invoke(format_params.clj:117)
	at ring.middleware.format_params$wrap_format_params$fn__45854.invoke(format_params.clj:119)
	at ring.middleware.format_params$wrap_format_params$fn__45854.invoke(format_params.clj:119)
	at compojure.api.middleware$wrap_exceptions$fn__46321.invoke(middleware.clj:43)
	at ring.middleware.format_response$wrap_format_response$fn__46023.invoke(format_response.clj:194)
	at ring.middleware.keyword_params$wrap_keyword_params$fn__46155.invoke(keyword_params.clj:36)
	at ring.middleware.nested_params$wrap_nested_params$fn__46205.invoke(nested_params.clj:89)
	at ring.middleware.params$wrap_params$fn__46253.invoke(params.clj:67)
	at compojure.api.middleware$wrap_options$fn__46331.invoke(middleware.clj:74)
	at compojure.api.routes.Route.invoke(routes.clj:74)
	at ring.middleware.cors$handle_cors.invokeStatic(cors.clj:164)
	at ring.middleware.cors$handle_cors.invoke(cors.clj:153)
	at ring.middleware.cors$wrap_cors$fn__53550.invoke(cors.clj:178)
	at ctia.http.middleware.auth$testable_wrap_authentication$fn__47349.invoke(auth.clj:22)
	at ctia.auth.jwt$wrap_jwt_to_ctia_auth$fn__44251.invoke(jwt.clj:28)
	at ring_jwt_middleware.core$wrap_jwt_auth_fn$fn__53339$fn__53340.invoke(core.clj:170)
	at ring.middleware.params$wrap_params$fn__46253.invoke(params.clj:67)
	at ring.adapter.jetty$proxy_handler$fn__53467.invoke(jetty.clj:25)
	at ring.adapter.jetty.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:258)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)
```

I thought perhaps this was due to it trying to perform an operation on a list of entities before any entities exist in the backing store, so I tried importing a simpler bundle that did not use the same external ID prefix.  I get the same NPE despite this.

**Comment by saintx** [comment]
Changing the configuration from `ctia.store.external-key-prefixes=cisco-,ctia-,hydrant-` to `ctia.store.external-key-prefixes=cisco-,ctia-` allows me to post bundles again without the NPE, but resumes the duplication behavior.

**Comment by hshahman** [comment]
Verified in rel-20180312 v0.2
