### ISSUE TITLE
Getting NPE while calling clojure.spec.alpha/valid?

### ISSUE THREAD

**Issue by gbuisson** [threatgrid/ctia#648]
Trying to integrate the Scratchpad entity, I get a stack trace at the flow validation step:

This code (with both arguments non-nil) fails:

```clojure
(when-not (cs/valid? spec entity)
        (throw (http-response/bad-request!
                {:error (cs/explain-str spec entity)
                 :entity entity})))
````
```
java.lang.NullPointerException
	at clojure.spec.alpha$spec_impl$reify__1987.conform_STAR_(alpha.clj:875)
	at clojure.spec.alpha$conform.invokeStatic(alpha.clj:150)
	at clojure.spec.alpha$conform.invoke(alpha.clj:146)
	at clojure.spec.alpha$map_spec_impl$reify__1931.conform_STAR_(alpha.clj:794)
	at clojure.spec.alpha$every_impl$reify__2182.conform_STAR_(alpha.clj:1245)
	at clojure.spec.alpha$conform.invokeStatic(alpha.clj:150)
	at clojure.spec.alpha$conform.invoke(alpha.clj:146)
	at clojure.spec.alpha$map_spec_impl$reify__1931.conform_STAR_(alpha.clj:794)
	at clojure.spec.alpha$conform.invokeStatic(alpha.clj:150)
	at clojure.spec.alpha$conform.invoke(alpha.clj:146)
	at clojure.spec.alpha$map_spec_impl$reify__1931.conform_STAR_(alpha.clj:794)
	at clojure.spec.alpha$valid_QMARK_.invokeStatic(alpha.clj:755)
	at clojure.spec.alpha$valid_QMARK_.invoke(alpha.clj:751)
	at ctia.flows.crud$eval21849$validate_entities__21854$fn__21858.invoke(crud.clj:91)
	at ctia.flows.crud$eval21849$validate_entities__21854.invoke(crud.clj:87)
	at ctia.flows.crud$create_flow.invokeStatic(crud.clj:315)
	at ctia.flows.crud$create_flow.doInvoke(crud.clj:299)
	at clojure.lang.RestFn.invoke(RestFn.java:2088)
	at ctia.http.routes.scratchpad$fn__59516$fn__59518.invoke(scratchpad.clj:34)
```

**Comment by gbuisson** [comment]
from my debugging session:

(cs/valid? :new-scratchpad/map (assoc-in new-scratchpad-maximal [:bundle :indicators] #{})) => true

**Comment by gbuisson** [comment]
so the bug seems to be in `flanders.utils/replace-either-with-any`: 

```clojure
(s/valid?
         (fs/->spec i/Indicator kwns)
         e/indicator-maximal) => true
```

```clojure
(s/valid?
         (fs/->spec (flanders.utils/replace-either-with-any i/Indicator) kwns)
         e/indicator-maximal) => exception
```

**Comment by gbuisson** [comment]
OK, so the bug occurs only with schemas where we replace conditionals/either with any, to match swagger spec requirements. that's why it passes the ctim.examples* tests.
the issue is that the `Anything` type produces a "nil" spec, and that triggers the exception on CTIA when we call `valid?`.
I found the fix for flanders.

**Comment by gbuisson** [comment]
flanders issue: https://github.com/threatgrid/flanders/issues/22
