### ISSUE TITLE
GraphQL throws an exception when the query contains an inner Fragment

### ISSUE THREAD

**Issue by msprunck** [threatgrid/ctia#658]
The following GraphQL query does not work:

```graphql
query WithInnerFragment {
  observable(type:"sha1", value:"8305cb9f39638dad87bbc1bfb84f8de1630e2b32") {
    type
    value
    judgements {
      nodes {
         type
         relationships {
          nodes {
            target_ref
            target_entity {
              ...on Indicator {
                type
              }
            }
          }
        }
      }
    }
  }
}
```
Result:

```json
{
  "errors": [
    "ExceptionWhileDataFetching{path=[observable]exception=java.lang.IllegalArgumentException: No matching field found: getName for class graphql.language.InlineFragmentlocations=[SourceLocation{line=2, column=3}]}"
  ],
  "data": {
    "observable": null
  }
}
```

The same query with a defined fragment returns a result:

```graphql
query WithoutInnerFragment {
  observable(type:"sha1", value:"8305cb9f39638dad87bbc1bfb84f8de1630e2b32") {
    type
    value
    judgements {
      nodes {
         type
         relationships {
          nodes {
            target_ref
            target_entity {
              ...indicatorFields
            }
          }
        }
      }
    }
  }
}

fragment indicatorFields on Indicator {
  type
}
```

Result:

```json
{
  "data": {
    "observable": {
      "type": "sha1",
      "value": "8305cb9f39638dad87bbc1bfb84f8de1630e2b32",
      "judgements": {
        "nodes": [
          {
            "type": "judgement",
            "relationships": {
              "nodes": [
                {
                  "target_ref": "http://localhost:3000/ctia/indicator/indicator-fb04fafb-a814-486e-a161-3a9ed8bc3d90",
                  "target_entity": {
                    "type": "indicator"
                  }
                }
              ]
            }
          }
        ]
      }
    }
  }
}
```

**Comment by msprunck** [comment]
The corresponding stacktrace

```java
2018-02-28 14:28:10,587 WARN (qtp378546236-34 - /ctia/graphql) [graphql.execution.SimpleDataFetcherExceptionHandler] - Exception while fetching data (/observable) : No matching field found: getName for class graphql.language.InlineFragment
java.lang.IllegalArgumentException: No matching field found: getName for class graphql.language.InlineFragment
	at clojure.lang.Reflector.getInstanceField(Reflector.java:271)
	at clojure.lang.Reflector.invokeNoArgInstanceMember(Reflector.java:315)
	at ctia.schemas.graphql.helpers$fields__GT_selections.invokeStatic(helpers.clj:153)
	at ctia.schemas.graphql.helpers$fields__GT_selections.invoke(helpers.clj:137)
	at ctia.schemas.graphql.helpers$fields__GT_selections.invokeStatic(helpers.clj:154)
	at ctia.schemas.graphql.helpers$fields__GT_selections.invoke(helpers.clj:137)
	at ctia.schemas.graphql.helpers$fields__GT_selections.invokeStatic(helpers.clj:154)
	at ctia.schemas.graphql.helpers$fields__GT_selections.invoke(helpers.clj:137)
	at ctia.schemas.graphql.helpers$fields__GT_selections.invokeStatic(helpers.clj:154)
	at ctia.schemas.graphql.helpers$fields__GT_selections.invoke(helpers.clj:137)
	at ctia.schemas.graphql.helpers$fields__GT_selections.invokeStatic(helpers.clj:154)
	at ctia.schemas.graphql.helpers$fields__GT_selections.invoke(helpers.clj:137)
	at ctia.schemas.graphql.helpers$fields__GT_selections.invokeStatic(helpers.clj:154)
	at ctia.schemas.graphql.helpers$fields__GT_selections.invoke(helpers.clj:137)
	at ctia.schemas.graphql.helpers$fn__62272$env__GT_field_selection__62277$fn__62278.invoke(helpers.clj:175)
	at ctia.schemas.graphql.helpers$fn__62272$env__GT_field_selection__62277.invoke(helpers.clj:163)
	at ctia.schemas.graphql.helpers$fn$reify__62297.get(helpers.clj:193)
	at graphql.execution.ExecutionStrategy.fetchField(ExecutionStrategy.java:219)
	at graphql.execution.ExecutionStrategy.resolveField(ExecutionStrategy.java:165)
	at graphql.execution.AsyncExecutionStrategy.execute(AsyncExecutionStrategy.java:55)
	at graphql.execution.Execution.executeOperation(Execution.java:154)
	at graphql.execution.Execution.execute(Execution.java:98)
	at graphql.GraphQL.execute(GraphQL.java:546)
	at graphql.GraphQL.parseValidateAndExecute(GraphQL.java:488)
	at graphql.GraphQL.executeAsync(GraphQL.java:463)
	at graphql.GraphQL.execute(GraphQL.java:394)
	at graphql.GraphQL.execute(GraphQL.java:353)
	at ctia.schemas.graphql.helpers$execute.invokeStatic(helpers.clj:392)
	at ctia.schemas.graphql.helpers$execute.invoke(helpers.clj:385)
	at ctia.schemas.graphql$execute.invokeStatic(graphql.clj:128)
	at ctia.schemas.graphql$execute.invoke(graphql.clj:127)
	at ctia.http.routes.graphql$fn__63165.invokeStatic(graphql.clj:41)
	at ctia.http.routes.graphql$fn__63165.invoke(graphql.clj:28)
	at compojure.core$wrap_response$fn__54994.invoke(core.clj:158)
	at compojure.core$pre_init$fn__55045.invoke(core.clj:328)
	at compojure.api.coerce$body_coercer_middleware$fn__56573.invoke(coerce.clj:51)
	at compojure.core$pre_init$fn__55047$fn__55050.invoke(core.clj:335)
	at compojure.core$wrap_route_middleware$fn__54978.invoke(core.clj:127)
	at compojure.core$wrap_route_info$fn__54983.invoke(core.clj:137)
	at compojure.core$wrap_route_matches$fn__54987.invoke(core.clj:146)
	at compojure.core$wrap_routes$fn__55057.invoke(core.clj:348)
	at compojure.api.routes.Route.invoke(routes.clj:74)
	at compojure.api.core$handle$fn__56726.invoke(core.clj:8)
	at clojure.core$some.invokeStatic(core.clj:2693)
	at clojure.core$some.invoke(core.clj:2684)
	at compojure.api.core$handle.invokeStatic(core.clj:8)
	at compojure.api.core$handle.invoke(core.clj:7)
	at clojure.core$partial$fn__5561.invoke(core.clj:2616)
	at compojure.api.routes.Route.invoke(routes.clj:74)
	at compojure.core$routing$fn__55002.invoke(core.clj:185)
	at clojure.core$some.invokeStatic(core.clj:2693)
	at clojure.core$some.invoke(core.clj:2684)
	at compojure.core$routing.invokeStatic(core.clj:185)
	at compojure.core$routing.doInvoke(core.clj:182)
	at clojure.lang.RestFn.applyTo(RestFn.java:139)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$apply.invoke(core.clj:652)
	at compojure.core$routes$fn__55006.invoke(core.clj:192)
	at compojure.core$routing$fn__55002.invoke(core.clj:185)
	at clojure.core$some.invokeStatic(core.clj:2693)
	at clojure.core$some.invoke(core.clj:2684)
	at compojure.core$routing.invokeStatic(core.clj:185)
	at compojure.core$routing.doInvoke(core.clj:182)
	at clojure.lang.RestFn.applyTo(RestFn.java:139)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$apply.invoke(core.clj:652)
	at compojure.core$routes$fn__55006.invoke(core.clj:192)
	at compojure.core$make_context$handler__55034.invoke(core.clj:285)
	at compojure.core$make_context$fn__55036.invoke(core.clj:293)
	at compojure.api.routes.Route.invoke(routes.clj:74)
	at compojure.api.core$handle$fn__56726.invoke(core.clj:8)
	at clojure.core$some.invokeStatic(core.clj:2693)
	at clojure.core$some.invoke(core.clj:2684)
	at compojure.api.core$handle.invokeStatic(core.clj:8)
	at compojure.api.core$handle.invoke(core.clj:7)
	at clojure.core$partial$fn__5561.invoke(core.clj:2616)
	at compojure.api.routes.Route.invoke(routes.clj:74)
	at metrics.ring.instrument$handle_request$fn__54381.invoke(instrument.clj:65)
	at metrics.ring.instrument.proxy$java.lang.Object$Callable$7da976d4.call(Unknown Source)
	at com.codahale.metrics.Timer.time(Timer.java:101)
	at metrics.ring.instrument$handle_request.invokeStatic(instrument.clj:64)
	at metrics.ring.instrument$handle_request.invoke(instrument.clj:54)
	at metrics.ring.instrument$instrument$fn__54389.invoke(instrument.clj:91)
	at clj_momo.ring.middleware.metrics$gen_metrics_for$fn__54451$fn__54452.invoke(metrics.clj:59)
	at clj_momo.ring.middleware.metrics.proxy$java.lang.Object$Callable$7da976d4.call(Unknown Source)
	at com.codahale.metrics.Timer.time(Timer.java:101)
	at clj_momo.ring.middleware.metrics$gen_metrics_for$fn__54451.invoke(metrics.clj:59)
	at ctia.http.middleware.cache_control$wrap_cache_control$fn__57747.invoke(cache_control.clj:30)
	at ring.middleware.not_modified$wrap_not_modified$fn__56784.invoke(not_modified.clj:53)
	at compojure.api.routes.Route.invoke(routes.clj:74)
	at compojure.api.core$handle$fn__56726.invoke(core.clj:8)
	at clojure.core$some.invokeStatic(core.clj:2693)
	at clojure.core$some.invoke(core.clj:2684)
	at compojure.api.core$handle.invokeStatic(core.clj:8)
	at compojure.api.core$handle.invoke(core.clj:7)
	at clojure.core$partial$fn__5561.invoke(core.clj:2616)
	at compojure.api.routes.Route.invoke(routes.clj:74)
	at ring.swagger.middleware$wrap_swagger_data$fn__56259.invoke(middleware.clj:35)
	at ring.middleware.http_response$wrap_http_response$fn__56110.invoke(http_response.clj:19)
	at ring.swagger.middleware$wrap_swagger_data$fn__56259.invoke(middleware.clj:35)
	at compojure.api.middleware$wrap_options$fn__56320.invoke(middleware.clj:74)
	at ring.middleware.format_params$wrap_format_params$fn__55843.invoke(format_params.clj:117)
	at ring.middleware.format_params$wrap_format_params$fn__55843.invoke(format_params.clj:119)
	at ring.middleware.format_params$wrap_format_params$fn__55843.invoke(format_params.clj:119)
	at ring.middleware.format_params$wrap_format_params$fn__55843.invoke(format_params.clj:119)
	at ring.middleware.format_params$wrap_format_params$fn__55843.invoke(format_params.clj:119)
	at compojure.api.middleware$wrap_exceptions$fn__56310.invoke(middleware.clj:43)
	at ring.middleware.format_response$wrap_format_response$fn__56012.invoke(format_response.clj:194)
	at ring.middleware.keyword_params$wrap_keyword_params$fn__56144.invoke(keyword_params.clj:36)
	at ring.middleware.nested_params$wrap_nested_params$fn__56194.invoke(nested_params.clj:89)
	at ring.middleware.params$wrap_params$fn__56242.invoke(params.clj:67)
	at compojure.api.middleware$wrap_options$fn__56320.invoke(middleware.clj:74)
	at compojure.api.routes.Route.invoke(routes.clj:74)
	at ring.middleware.cors$handle_cors.invokeStatic(cors.clj:161)
	at ring.middleware.cors$handle_cors.invoke(cors.clj:153)
	at ring.middleware.cors$wrap_cors$fn__63845.invoke(cors.clj:178)
	at ctia.http.middleware.auth$testable_wrap_authentication$fn__57340.invoke(auth.clj:22)
	at ctia.auth.jwt$wrap_jwt_to_ctia_auth$fn__54240.invoke(jwt.clj:54)
	at ring_jwt_middleware.core$wrap_jwt_auth_fn$fn__63606$fn__63607.invoke(core.clj:235)
	at ring.middleware.params$wrap_params$fn__56242.invoke(params.clj:67)
	at ring.adapter.jetty$proxy_handler$fn__63762.invoke(jetty.clj:25)
	at ring.adapter.jetty.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:258)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:748)
```
