### ISSUE TITLE
Getting 400 error when investigating pki_serial in /iroh-enrich/observe/observables endpoint

### ISSUE THREAD

**Issue by hshahman** [threatgrid/ctia#711]
Related to: https://github.com/threatgrid/ctia/pull/704
Env: TEST

Based on https://github.com/threatgrid/ctia/pull/704, we changed pki-serial to pki_serial, but hitting the `https://visibility.test.iroh.site/iroh/iroh-enrich/observe/observables` endpoint by an entity type `pki_serial` returns a 400 error.

CURL:
```
curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' --header 'Authorization: Bearer <JWT_TOKEN>' -d '[ \ 
   { \ 
     "value": "12344444", \ 
     "type": "pki_serial" \ 
   } \ 
 ]' 'https://visibility.test.iroh.site/iroh/iroh-enrich/observe/observables'
```

Response:
```
{
  "errors": [
    {
      "type": "(not (#{\"file_path\" \"mac_address\" \"device\" \"hostname\" \"url\" \"pki-serial\" \"user\" \"ipv6\" \"email\" \"sha256\" \"sha1\" \"md5\" \"ip\" \"domain\" \"imei\" \"amp_computer_guid\" \"imsi\" \"amp-device\" \"file_name\"} \"pki_serial\"))"
    }
  ]
}
```

Kibana log:
```
2018-05-12 00:04:12,822 ERROR (qtp1562346831-20 - /ctia/pki-serial/1232131/verdict) [ctia.http.exceptions] - Request validation failed: {:observable_type (not (#{"file_path" "mac_address" "device" "hostname" "url" "user" "ipv6" "email" "sha256" "sha1" "md5" "ip" "domain" "imei" "amp_computer_guid" "pki_serial" "imsi" "file_name"} "pki-serial"))} - Meta: #schema.utils.ErrorContainer{:error {:observable_type (not (#{"file_path" "mac_address" "device" "hostname" "url" "user" "ipv6" "email" "sha256" "sha1" "md5" "ip" "domain" "imei" "amp_computer_guid" "pki_serial" "imsi" "file_name"} "pki-serial"))}, :type :compojure.api.exception/request-validation}
clojure.lang.ExceptionInfo: Request validation failed: {:observable_type (not (#{"file_path" "mac_address" "device" "hostname" "url" "user" "ipv6" "email" "sha256" "sha1" "md5" "ip" "domain" "imei" "amp_computer_guid" "pki_serial" "imsi" "file_name"} "pki-serial"))} schema.utils.ErrorContainer@70945aaf
	at clojure.core$ex_info.invokeStatic(core.clj:4739)
	at clojure.core$ex_info.invoke(core.clj:4739)
	at compojure.api.coerce$coerce_BANG_.invokeStatic(coerce.clj:61)
	at compojure.api.coerce$coerce_BANG_.invoke(coerce.clj:53)
	at ctia.observable.routes$fn__59073.invokeStatic(routes.clj:27)
	at ctia.observable.routes$fn__59073.invoke(routes.clj:27)
	at compojure.core$wrap_response$fn__30413.invoke(core.clj:158)
	at compojure.core$pre_init$fn__30464.invoke(core.clj:328)
	at compojure.api.coerce$body_coercer_middleware$fn__32469.invoke(coerce.clj:51)
	at compojure.core$pre_init$fn__30466$fn__30469.invoke(core.clj:335)
	at compojure.core$wrap_route_middleware$fn__30397.invoke(core.clj:127)
	at compojure.core$wrap_route_info$fn__30402.invoke(core.clj:137)
	at compojure.core$wrap_route_matches$fn__30406.invoke(core.clj:146)
	at compojure.core$wrap_routes$fn__30476.invoke(core.clj:348)
	at compojure.api.routes.Route.invoke(routes.clj:74)
	at compojure.api.core$handle$fn__32646.invoke(core.clj:8)
	at clojure.core$some.invokeStatic(core.clj:2693)
	at clojure.core$some.invoke(core.clj:2684)
	at compojure.api.core$handle.invokeStatic(core.clj:8)
	at compojure.api.core$handle.invoke(core.clj:7)
	at clojure.core$partial$fn__5561.invoke(core.clj:2616)
	at compojure.api.routes.Route.invoke(routes.clj:74)
	at compojure.core$routing$fn__30421.invoke(core.clj:185)
	at clojure.core$some.invokeStatic(core.clj:2693)
	at clojure.core$some.invoke(core.clj:2684)
	at compojure.core$routing.invokeStatic(core.clj:185)
	at compojure.core$routing.doInvoke(core.clj:182)
	at clojure.lang.RestFn.applyTo(RestFn.java:139)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$apply.invoke(core.clj:652)
	at compojure.core$routes$fn__30425.invoke(core.clj:192)
	at compojure.core$routing$fn__30421.invoke(core.clj:185)
	at clojure.core$some.invokeStatic(core.clj:2693)
	at clojure.core$some.invoke(core.clj:2684)
	at compojure.core$routing.invokeStatic(core.clj:185)
	at compojure.core$routing.doInvoke(core.clj:182)
	at clojure.lang.RestFn.applyTo(RestFn.java:139)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$apply.invoke(core.clj:652)
	at compojure.core$routes$fn__30425.invoke(core.clj:192)
	at compojure.core$make_context$handler__30453.invoke(core.clj:285)
	at compojure.core$make_context$fn__30455.invoke(core.clj:293)
	at compojure.api.routes.Route.invoke(routes.clj:74)
	at compojure.api.core$handle$fn__32646.invoke(core.clj:8)
	at clojure.core$some.invokeStatic(core.clj:2693)
	at clojure.core$some.invoke(core.clj:2684)
	at compojure.api.core$handle.invokeStatic(core.clj:8)
	at compojure.api.core$handle.invoke(core.clj:7)
	at clojure.core$partial$fn__5561.invoke(core.clj:2616)
	at compojure.api.routes.Route.invoke(routes.clj:74)
	at metrics.ring.instrument$handle_request$fn__57289.invoke(instrument.clj:65)
	at metrics.ring.instrument.proxy$java.lang.Object$Callable$7da976d4.call(Unknown Source)
	at com.codahale.metrics.Timer.time(Timer.java:101)
	at metrics.ring.instrument$handle_request.invokeStatic(instrument.clj:64)
	at metrics.ring.instrument$handle_request.invoke(instrument.clj:54)
	at metrics.ring.instrument$instrument$fn__57297.invoke(instrument.clj:91)
	at clj_momo.ring.middleware.metrics$gen_metrics_for$fn__57359$fn__57360.invoke(metrics.clj:59)
	at clj_momo.ring.middleware.metrics.proxy$java.lang.Object$Callable$7da976d4.call(Unknown Source)
	at com.codahale.metrics.Timer.time(Timer.java:101)
	at clj_momo.ring.middleware.metrics$gen_metrics_for$fn__57359.invoke(metrics.clj:59)
	at ctia.http.middleware.version$wrap_version$fn__59003.invoke(version.clj:9)
	at ctia.http.middleware.cache_control$wrap_cache_control$fn__58985.invoke(cache_control.clj:29)
	at ring.middleware.not_modified$wrap_not_modified$fn__32702.invoke(not_modified.clj:53)
	at compojure.api.routes.Route.invoke(routes.clj:74)
	at compojure.api.core$handle$fn__32646.invoke(core.clj:8)
	at clojure.core$some.invokeStatic(core.clj:2693)
	at clojure.core$some.invoke(core.clj:2684)
	at compojure.api.core$handle.invokeStatic(core.clj:8)
	at compojure.api.core$handle.invoke(core.clj:7)
	at clojure.core$partial$fn__5561.invoke(core.clj:2616)
	at compojure.api.routes.Route.invoke(routes.clj:74)
	at ring.swagger.middleware$wrap_swagger_data$fn__32155.invoke(middleware.clj:35)
	at ring.middleware.http_response$wrap_http_response$fn__32014.invoke(http_response.clj:19)
	at ring.swagger.middleware$wrap_swagger_data$fn__32155.invoke(middleware.clj:35)
	at compojure.api.middleware$wrap_options$fn__32216.invoke(middleware.clj:74)
	at ring.middleware.format_params$wrap_format_params$fn__31747.invoke(format_params.clj:119)
	at ring.middleware.format_params$wrap_format_params$fn__31747.invoke(format_params.clj:119)
	at ring.middleware.format_params$wrap_format_params$fn__31747.invoke(format_params.clj:119)
	at ring.middleware.format_params$wrap_format_params$fn__31747.invoke(format_params.clj:119)
	at ring.middleware.format_params$wrap_format_params$fn__31747.invoke(format_params.clj:119)
	at compojure.api.middleware$wrap_exceptions$fn__32206.invoke(middleware.clj:43)
	at ring.middleware.format_response$wrap_format_response$fn__31916.invoke(format_response.clj:194)
	at ring.middleware.keyword_params$wrap_keyword_params$fn__32048.invoke(keyword_params.clj:36)
	at ring.middleware.nested_params$wrap_nested_params$fn__32098.invoke(nested_params.clj:89)
	at ring.middleware.params$wrap_params$fn__32146.invoke(params.clj:67)
	at compojure.api.middleware$wrap_options$fn__32216.invoke(middleware.clj:74)
	at compojure.api.routes.Route.invoke(routes.clj:74)
	at ring.middleware.cors$handle_cors.invokeStatic(cors.clj:164)
	at ring.middleware.cors$handle_cors.invoke(cors.clj:153)
	at ring.middleware.cors$wrap_cors$fn__59528.invoke(cors.clj:178)
	at ctia.http.middleware.auth$testable_wrap_authentication$fn__32622.invoke(auth.clj:22)
	at ctia.auth.jwt$wrap_jwt_to_ctia_auth$fn__57255.invoke(jwt.clj:145)
	at ring_jwt_middleware.core$wrap_jwt_auth_fn$fn__57130$fn__57131.invoke(core.clj:268)
	at ring.middleware.params$wrap_params$fn__32146.invoke(params.clj:67)
	at ring.adapter.jetty$proxy_handler$fn__59445.invoke(jetty.clj:25)
	at ring.adapter.jetty.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:258)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by gbuisson** [comment]
This means that IROH doesn't use the latest CTIM version

**Comment by hshahman** [comment]
Verified in rel-v1.3
