### ISSUE TITLE
Sometimes getting 401 error from casebook when login to UI

### ISSUE THREAD

**Issue by hshahman** [threatgrid/ctia#739]
Env: TEST

It is not a persistent issue. I saw 401 errors from Casebook several times even after logout/login and refreshing the browser. When I made a new casebook, the 401 error went away. 

Kibana log:
```
2018-09-05 16:46:23,215 INFO (qtp1244605474-24 - /ctia/casebook/casebook-612fb2ca-7fbd-432c-a50c-9c7fbb410825?casebook-612fb2ca-7fbd-432c-a50c-9c7fbb410825) [ctia.http.exceptions] - You are not allowed to read this document - Meta: {:type :access-control-error}
clojure.lang.ExceptionInfo: You are not allowed to read this document {:type :access-control-error}
	at clojure.core$ex_info.invokeStatic(core.clj:4739)
	at clojure.core$ex_info.invoke(core.clj:4739)
	at ctia.stores.es.crud$handle_read$fn39719__39732$fn__39733.invoke(crud.clj:151)
	at ctia.stores.es.crud$handle_read$fn39719__39732.invoke(crud.clj:139)
	at clojure.lang.AFn.applyToHelper(AFn.java:165)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.lang.AFunction$1.doInvoke(AFunction.java:29)
	at clojure.lang.RestFn.invoke(RestFn.java:457)
	at ctia.entity.casebook.CasebookStore.read_record(casebook.clj:76)
	at ctia.store$fn__17542$G__17498__17547.invoke(store.clj:5)
	at ctia.store$fn__17542$G__17497__17553.invoke(store.clj:5)
	at clojure.lang.AFn.applyToHelper(AFn.java:165)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$apply.invoke(core.clj:652)
	at ctia.store$read_store.invokeStatic(store.clj:59)
	at ctia.store$read_store.doInvoke(store.clj:58)
	at clojure.lang.RestFn.invoke(RestFn.java:490)
	at ctia.http.routes.crud$entity_crud_routes$fn__37830.invoke(crud.clj:188)
	at compojure.core$wrap_response$fn__21252.invoke(core.clj:158)
	at compojure.core$pre_init$fn__21303.invoke(core.clj:328)
	at compojure.api.coerce$body_coercer_middleware$fn__24538.invoke(coerce.clj:51)
	at compojure.core$pre_init$fn__21305$fn__21308.invoke(core.clj:335)
	at compojure.core$wrap_route_middleware$fn__21236.invoke(core.clj:127)
	at compojure.core$wrap_route_info$fn__21241.invoke(core.clj:137)
	at compojure.core$wrap_route_matches$fn__21245.invoke(core.clj:146)
	at compojure.core$wrap_routes$fn__21315.invoke(core.clj:348)
	at compojure.api.routes.Route.invoke(routes.clj:74)
	at compojure.api.core$handle$fn__24719.invoke(core.clj:8)
	at clojure.core$some.invokeStatic(core.clj:2693)
	at clojure.core$some.invoke(core.clj:2684)
	at compojure.api.core$handle.invokeStatic(core.clj:8)
	at compojure.api.core$handle.invoke(core.clj:7)
	at clojure.core$partial$fn__5561.invoke(core.clj:2616)
	at compojure.api.routes.Route.invoke(routes.clj:74)
	at compojure.api.core$handle$fn__24719.invoke(core.clj:8)
	at clojure.core$some.invokeStatic(core.clj:2693)
	at clojure.core$some.invoke(core.clj:2684)
	at compojure.api.core$handle.invokeStatic(core.clj:8)
	at compojure.api.core$handle.invoke(core.clj:7)
	at clojure.core$partial$fn__5561.invoke(core.clj:2616)
	at compojure.api.routes.Route.invoke(routes.clj:74)
	at compojure.core$routing$fn__21260.invoke(core.clj:185)
	at clojure.core$some.invokeStatic(core.clj:2693)
	at clojure.core$some.invoke(core.clj:2684)
	at compojure.core$routing.invokeStatic(core.clj:185)
	at compojure.core$routing.doInvoke(core.clj:182)
	at clojure.lang.RestFn.applyTo(RestFn.java:139)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$apply.invoke(core.clj:652)
	at compojure.core$routes$fn__21264.invoke(core.clj:192)
	at compojure.core$routing$fn__21260.invoke(core.clj:185)
	at clojure.core$some.invokeStatic(core.clj:2693)
	at clojure.core$some.invoke(core.clj:2684)
	at compojure.core$routing.invokeStatic(core.clj:185)
	at compojure.core$routing.doInvoke(core.clj:182)
	at clojure.lang.RestFn.applyTo(RestFn.java:139)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$apply.invoke(core.clj:652)
	at compojure.core$routes$fn__21264.invoke(core.clj:192)
	at compojure.core$make_context$handler__21292.invoke(core.clj:285)
	at compojure.core$make_context$fn__21294.invoke(core.clj:293)
	at compojure.api.routes.Route.invoke(routes.clj:74)
	at compojure.api.core$handle$fn__24719.invoke(core.clj:8)
	at clojure.core$some.invokeStatic(core.clj:2693)
	at clojure.core$some.invoke(core.clj:2684)
	at compojure.api.core$handle.invokeStatic(core.clj:8)
	at compojure.api.core$handle.invoke(core.clj:7)
	at clojure.core$partial$fn__5561.invoke(core.clj:2616)
	at compojure.api.routes.Route.invoke(routes.clj:74)
	at compojure.api.core$handle$fn__24719.invoke(core.clj:8)
	at clojure.core$some.invokeStatic(core.clj:2693)
	at clojure.core$some.invoke(core.clj:2684)
	at compojure.api.core$handle.invokeStatic(core.clj:8)
	at compojure.api.core$handle.invoke(core.clj:7)
	at clojure.core$partial$fn__5561.invoke(core.clj:2616)
	at compojure.api.routes.Route.invoke(routes.clj:74)
	at ctia.http.middleware.auth$wrap_authenticated$fn__24696.invoke(auth.clj:40)
	at compojure.api.routes.Route.invoke(routes.clj:74)
	at compojure.core$routing$fn__21260.invoke(core.clj:185)
	at clojure.core$some.invokeStatic(core.clj:2693)
	at clojure.core$some.invoke(core.clj:2684)
	at compojure.core$routing.invokeStatic(core.clj:185)
	at compojure.core$routing.doInvoke(core.clj:182)
	at clojure.lang.RestFn.applyTo(RestFn.java:139)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$apply.invoke(core.clj:652)
	at compojure.core$routes$fn__21264.invoke(core.clj:192)
	at compojure.core$routing$fn__21260.invoke(core.clj:185)
	at clojure.core$some.invokeStatic(core.clj:2693)
	at clojure.core$some.invoke(core.clj:2684)
	at compojure.core$routing.invokeStatic(core.clj:185)
	at compojure.core$routing.doInvoke(core.clj:182)
	at clojure.lang.RestFn.applyTo(RestFn.java:139)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$apply.invoke(core.clj:652)
	at compojure.core$routes$fn__21264.invoke(core.clj:192)
	at compojure.core$make_context$handler__21292.invoke(core.clj:285)
	at compojure.core$make_context$fn__21294.invoke(core.clj:293)
	at compojure.api.routes.Route.invoke(routes.clj:74)
	at compojure.api.core$handle$fn__24719.invoke(core.clj:8)
	at clojure.core$some.invokeStatic(core.clj:2693)
	at clojure.core$some.invoke(core.clj:2684)
	at compojure.api.core$handle.invokeStatic(core.clj:8)
	at compojure.api.core$handle.invoke(core.clj:7)
	at clojure.core$partial$fn__5561.invoke(core.clj:2616)
	at compojure.api.routes.Route.invoke(routes.clj:74)
	at metrics.ring.instrument$handle_request$fn__60444.invoke(instrument.clj:65)
	at metrics.ring.instrument.proxy$java.lang.Object$Callable$7da976d4.call(Unknown Source)
	at com.codahale.metrics.Timer.time(Timer.java:101)
	at metrics.ring.instrument$handle_request.invokeStatic(instrument.clj:64)
	at metrics.ring.instrument$handle_request.invoke(instrument.clj:54)
	at metrics.ring.instrument$instrument$fn__60452.invoke(instrument.clj:91)
	at clj_momo.ring.middleware.metrics$gen_metrics_for$fn__60514$fn__60515.invoke(metrics.clj:59)
	at clj_momo.ring.middleware.metrics.proxy$java.lang.Object$Callable$7da976d4.call(Unknown Source)
	at com.codahale.metrics.Timer.time(Timer.java:101)
	at clj_momo.ring.middleware.metrics$gen_metrics_for$fn__60514.invoke(metrics.clj:59)
	at ctia.http.middleware.version$wrap_version$fn__62183.invoke(version.clj:9)
	at ctia.http.middleware.cache_control$wrap_cache_control$fn__62165.invoke(cache_control.clj:29)
	at ring.middleware.not_modified$wrap_not_modified$fn__24775.invoke(not_modified.clj:53)
	at compojure.api.routes.Route.invoke(routes.clj:74)
	at compojure.api.core$handle$fn__24719.invoke(core.clj:8)
	at clojure.core$some.invokeStatic(core.clj:2693)
	at clojure.core$some.invoke(core.clj:2684)
	at compojure.api.core$handle.invokeStatic(core.clj:8)
	at compojure.api.core$handle.invoke(core.clj:7)
	at clojure.core$partial$fn__5561.invoke(core.clj:2616)
	at compojure.api.routes.Route.invoke(routes.clj:74)
	at ring.swagger.middleware$wrap_swagger_data$fn__24224.invoke(middleware.clj:35)
	at ring.middleware.http_response$wrap_http_response$fn__24083.invoke(http_response.clj:19)
	at ring.swagger.middleware$wrap_swagger_data$fn__24224.invoke(middleware.clj:35)
	at compojure.api.middleware$wrap_options$fn__24285.invoke(middleware.clj:74)
	at ring.middleware.format_params$wrap_format_params$fn__23224.invoke(format_params.clj:118)
	at ring.middleware.format_params$wrap_format_params$fn__23224.invoke(format_params.clj:119)
	at ring.middleware.format_params$wrap_format_params$fn__23224.invoke(format_params.clj:119)
	at ring.middleware.format_params$wrap_format_params$fn__23224.invoke(format_params.clj:119)
	at ring.middleware.format_params$wrap_format_params$fn__23224.invoke(format_params.clj:119)
	at compojure.api.middleware$wrap_exceptions$fn__24275.invoke(middleware.clj:43)
	at ring.middleware.format_response$wrap_format_response$fn__23985.invoke(format_response.clj:194)
	at ring.middleware.keyword_params$wrap_keyword_params$fn__24117.invoke(keyword_params.clj:36)
	at ring.middleware.nested_params$wrap_nested_params$fn__24167.invoke(nested_params.clj:89)
	at ring.middleware.params$wrap_params$fn__24215.invoke(params.clj:67)
	at compojure.api.middleware$wrap_options$fn__24285.invoke(middleware.clj:74)
	at compojure.api.routes.Route.invoke(routes.clj:74)
	at ctia.http.middleware.auth$testable_wrap_authentication$fn__24691.invoke(auth.clj:22)
	at ctia.auth.jwt$wrap_jwt_to_ctia_auth$fn__60410.invoke(jwt.clj:126)
	at ring_jwt_middleware.core$wrap_jwt_auth_fn$fn__60308$fn__60309.invoke(core.clj:268)
	at ring.middleware.cors$handle_cors.invokeStatic(cors.clj:161)
	at ring.middleware.cors$handle_cors.invoke(cors.clj:153)
	at ring.middleware.cors$wrap_cors$fn__62712.invoke(cors.clj:178)
	at ring.middleware.params$wrap_params$fn__24215.invoke(params.clj:67)
	at ring.adapter.jetty$proxy_handler$fn__62629.invoke(jetty.clj:25)
	at ring.adapter.jetty.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:258)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by gbuisson** [comment]
Unfortunately, unless you clear local storage, if the casebook widget doesn't manage correctly a user change you will still get this error, closing, reopen if it happens again in different circumstances.
