### ISSUE TITLE
Sending request to /ctia/event/{id} and /ctia/event/external_id/{external_id} results in 500 error message

### ISSUE THREAD

**Issue by hshahman** [threatgrid/ctia#748]
Env: TEST

Kibana:
```
2018-10-29 21:22:56,746 ERROR (qtp2018427981-22 - /ctia/event/event-9de16b5d-156a-48ab-9d68-ff146cbca138) [ctia.http.exceptions] - No implementation of method: :read-record of protocol: #'ctia.store/IStore found for class: ctia.entity.event.store.EventStore
java.lang.IllegalArgumentException: No implementation of method: :read-record of protocol: #'ctia.store/IStore found for class: ctia.entity.event.store.EventStore
	at clojure.core$_cache_protocol_fn.invokeStatic(core_deftype.clj:583)
	at clojure.core$_cache_protocol_fn.invoke(core_deftype.clj:575)
	at ctia.store$fn__17611$G__17566__17622.invoke(store.clj:5)
	at clojure.lang.AFn.applyToHelper(AFn.java:165)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$apply.invoke(core.clj:652)
	at ctia.store$read_store.invokeStatic(store.clj:59)
	at ctia.store$read_store.doInvoke(store.clj:58)
	at clojure.lang.RestFn.invoke(RestFn.java:490)
	at ctia.http.routes.crud$entity_crud_routes$fn__37883.invoke(crud.clj:191)
	at compojure.core$wrap_response$fn__21322.invoke(core.clj:158)
	at compojure.core$pre_init$fn__21373.invoke(core.clj:328)
	at compojure.api.coerce$body_coercer_middleware$fn__24608.invoke(coerce.clj:51)
	at compojure.core$pre_init$fn__21375$fn__21378.invoke(core.clj:335)
	at compojure.core$wrap_route_middleware$fn__21306.invoke(core.clj:127)
	at compojure.core$wrap_route_info$fn__21311.invoke(core.clj:137)
	at compojure.core$wrap_route_matches$fn__21315.invoke(core.clj:146)
	at compojure.core$wrap_routes$fn__21385.invoke(core.clj:348)
	at compojure.api.routes.Route.invoke(routes.clj:74)
	at compojure.api.core$handle$fn__24789.invoke(core.clj:8)
	at clojure.core$some.invokeStatic(core.clj:2693)
	at clojure.core$some.invoke(core.clj:2684)
	at compojure.api.core$handle.invokeStatic(core.clj:8)
	at compojure.api.core$handle.invoke(core.clj:7)
	at clojure.core$partial$fn__5561.invoke(core.clj:2616)
	at compojure.api.routes.Route.invoke(routes.clj:74)
	at compojure.core$routing$fn__21330.invoke(core.clj:185)
	at clojure.core$some.invokeStatic(core.clj:2693)
	at clojure.core$some.invoke(core.clj:2684)
	at compojure.core$routing.invokeStatic(core.clj:185)
	at compojure.core$routing.doInvoke(core.clj:182)
	at clojure.lang.RestFn.applyTo(RestFn.java:139)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$apply.invoke(core.clj:652)
	at compojure.core$routes$fn__21334.invoke(core.clj:192)
	at compojure.core$routing$fn__21330.invoke(core.clj:185)
	at clojure.core$some.invokeStatic(core.clj:2693)
	at clojure.core$some.invoke(core.clj:2684)
	at compojure.core$routing.invokeStatic(core.clj:185)
	at compojure.core$routing.doInvoke(core.clj:182)
	at clojure.lang.RestFn.applyTo(RestFn.java:139)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$apply.invoke(core.clj:652)
	at compojure.core$routes$fn__21334.invoke(core.clj:192)
	at compojure.core$make_context$handler__21362.invoke(core.clj:285)
	at compojure.core$make_context$fn__21364.invoke(core.clj:293)
	at compojure.api.routes.Route.invoke(routes.clj:74)
	at compojure.api.core$handle$fn__24789.invoke(core.clj:8)
	at clojure.core$some.invokeStatic(core.clj:2693)
	at clojure.core$some.invoke(core.clj:2684)
	at compojure.api.core$handle.invokeStatic(core.clj:8)
	at compojure.api.core$handle.invoke(core.clj:7)
	at clojure.core$partial$fn__5561.invoke(core.clj:2616)
	at compojure.api.routes.Route.invoke(routes.clj:74)
	at compojure.api.core$handle$fn__24789.invoke(core.clj:8)
	at clojure.core$some.invokeStatic(core.clj:2693)
	at clojure.core$some.invoke(core.clj:2684)
	at compojure.api.core$handle.invokeStatic(core.clj:8)
	at compojure.api.core$handle.invoke(core.clj:7)
	at clojure.core$partial$fn__5561.invoke(core.clj:2616)
	at compojure.api.routes.Route.invoke(routes.clj:74)
	at ctia.http.middleware.auth$wrap_authenticated$fn__24766.invoke(auth.clj:40)
	at compojure.api.routes.Route.invoke(routes.clj:74)
	at compojure.core$routing$fn__21330.invoke(core.clj:185)
	at clojure.core$some.invokeStatic(core.clj:2693)
	at clojure.core$some.invoke(core.clj:2684)
	at compojure.core$routing.invokeStatic(core.clj:185)
	at compojure.core$routing.doInvoke(core.clj:182)
	at clojure.lang.RestFn.applyTo(RestFn.java:139)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$apply.invoke(core.clj:652)
	at compojure.core$routes$fn__21334.invoke(core.clj:192)
	at compojure.core$routing$fn__21330.invoke(core.clj:185)
	at clojure.core$some.invokeStatic(core.clj:2693)
	at clojure.core$some.invoke(core.clj:2684)
	at compojure.core$routing.invokeStatic(core.clj:185)
	at compojure.core$routing.doInvoke(core.clj:182)
	at clojure.lang.RestFn.applyTo(RestFn.java:139)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$apply.invoke(core.clj:652)
	at compojure.core$routes$fn__21334.invoke(core.clj:192)
	at compojure.core$make_context$handler__21362.invoke(core.clj:285)
	at compojure.core$make_context$fn__21364.invoke(core.clj:293)
	at compojure.api.routes.Route.invoke(routes.clj:74)
	at compojure.api.core$handle$fn__24789.invoke(core.clj:8)
	at clojure.core$some.invokeStatic(core.clj:2693)
	at clojure.core$some.invoke(core.clj:2684)
	at compojure.api.core$handle.invokeStatic(core.clj:8)
	at compojure.api.core$handle.invoke(core.clj:7)
	at clojure.core$partial$fn__5561.invoke(core.clj:2616)
	at compojure.api.routes.Route.invoke(routes.clj:74)
	at metrics.ring.instrument$handle_request$fn__60593.invoke(instrument.clj:65)
	at metrics.ring.instrument.proxy$java.lang.Object$Callable$7da976d4.call(Unknown Source)
	at com.codahale.metrics.Timer.time(Timer.java:101)
	at metrics.ring.instrument$handle_request.invokeStatic(instrument.clj:64)
	at metrics.ring.instrument$handle_request.invoke(instrument.clj:54)
	at metrics.ring.instrument$instrument$fn__60601.invoke(instrument.clj:91)
	at clj_momo.ring.middleware.metrics$gen_metrics_for$fn__60663$fn__60664.invoke(metrics.clj:59)
	at clj_momo.ring.middleware.metrics.proxy$java.lang.Object$Callable$7da976d4.call(Unknown Source)
	at com.codahale.metrics.Timer.time(Timer.java:101)
	at clj_momo.ring.middleware.metrics$gen_metrics_for$fn__60663.invoke(metrics.clj:59)
	at ctia.http.middleware.version$wrap_version$fn__62332.invoke(version.clj:9)
	at ctia.http.middleware.cache_control$wrap_cache_control$fn__62314.invoke(cache_control.clj:29)
	at ring.middleware.not_modified$wrap_not_modified$fn__24845.invoke(not_modified.clj:53)
	at compojure.api.routes.Route.invoke(routes.clj:74)
	at compojure.api.core$handle$fn__24789.invoke(core.clj:8)
	at clojure.core$some.invokeStatic(core.clj:2693)
	at clojure.core$some.invoke(core.clj:2684)
	at compojure.api.core$handle.invokeStatic(core.clj:8)
	at compojure.api.core$handle.invoke(core.clj:7)
	at clojure.core$partial$fn__5561.invoke(core.clj:2616)
	at compojure.api.routes.Route.invoke(routes.clj:74)
	at ring.swagger.middleware$wrap_swagger_data$fn__24294.invoke(middleware.clj:35)
	at ring.middleware.http_response$wrap_http_response$fn__24153.invoke(http_response.clj:19)
	at ring.swagger.middleware$wrap_swagger_data$fn__24294.invoke(middleware.clj:35)
	at compojure.api.middleware$wrap_options$fn__24355.invoke(middleware.clj:74)
	at ring.middleware.format_params$wrap_format_params$fn__23294.invoke(format_params.clj:119)
	at ring.middleware.format_params$wrap_format_params$fn__23294.invoke(format_params.clj:119)
	at ring.middleware.format_params$wrap_format_params$fn__23294.invoke(format_params.clj:119)
	at ring.middleware.format_params$wrap_format_params$fn__23294.invoke(format_params.clj:119)
	at ring.middleware.format_params$wrap_format_params$fn__23294.invoke(format_params.clj:119)
	at compojure.api.middleware$wrap_exceptions$fn__24345.invoke(middleware.clj:43)
	at ring.middleware.format_response$wrap_format_response$fn__24055.invoke(format_response.clj:194)
	at ring.middleware.keyword_params$wrap_keyword_params$fn__24187.invoke(keyword_params.clj:36)
	at ring.middleware.nested_params$wrap_nested_params$fn__24237.invoke(nested_params.clj:89)
	at ring.middleware.params$wrap_params$fn__24285.invoke(params.clj:67)
	at compojure.api.middleware$wrap_options$fn__24355.invoke(middleware.clj:74)
	at compojure.api.routes.Route.invoke(routes.clj:74)
	at ctia.http.middleware.auth$testable_wrap_authentication$fn__24761.invoke(auth.clj:22)
	at ctia.auth.jwt$wrap_jwt_to_ctia_auth$fn__60559.invoke(jwt.clj:126)
	at ring_jwt_middleware.core$wrap_jwt_auth_fn$fn__60457$fn__60458.invoke(core.clj:268)
	at ring.middleware.cors$handle_cors.invokeStatic(cors.clj:164)
	at ring.middleware.cors$handle_cors.invoke(cors.clj:153)
	at ring.middleware.cors$wrap_cors$fn__62869.invoke(cors.clj:178)
	at ring.middleware.params$wrap_params$fn__24285.invoke(params.clj:67)
	at ring.adapter.jetty$proxy_handler$fn__62786.invoke(jetty.clj:25)
	at ring.adapter.jetty.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:258)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by hshahman** [comment]
`Get by external_id` endpoint has been disabled.

**Comment by gbuisson** [comment]
> `Get by external_id` endpoint has been disabled.

yes events can't have by external_id ;-)
