### ISSUE TITLE
POST and PUT '500' Errors returned by /ctia/casebook

### ISSUE THREAD

**Issue by johnejardine** [threatgrid/ctia#753]
Example POST error:
https://kibana-n.us-east-1.prod.iroh.site/app/kibana#/doc/48f8d930-44a9-11e8-b845-017474c8062b/logstash-2018.11.15/doc?id=8uSZFWcBrs7zRR1Q_ffA&_g=h@f4cbf52

Example PUT error:
https://kibana-n.us-east-1.prod.iroh.site/app/kibana#/doc/48f8d930-44a9-11e8-b845-017474c8062b/logstash-2018.11.14/doc?id=OfyrEWcBrs7zRR1QbFhX&_g=h@15e663b

Related stacktrace

```java
2018-11-15 04:21:10,642 ERROR (qtp284871259-21 - /ctia/casebook/casebook-1a4519f7-7546-48cd-8672-3540fd640742/observables) [ctia.http.exceptions] - Response validation failed: schema.utils.ValidationError@78672ded - Meta: #schema.utils.ErrorContainer{:error (not (map? nil)), :type :compojure.api.exception/response-validation, :response {:status 200, :headers {}, :body nil}}
clojure.lang.ExceptionInfo: Response validation failed: schema.utils.ValidationError@78672ded schema.utils.ErrorContainer@ceb53648
	at clojure.core$ex_info.invokeStatic(core.clj:4739)
	at clojure.core$ex_info.invoke(core.clj:4739)
	at compojure.api.coerce$coerce_response_BANG_.invokeStatic(coerce.clj:40)
	at compojure.api.coerce$coerce_response_BANG_.invoke(coerce.clj:31)
	at compojure.api.coerce$body_coercer_middleware$fn__24615.invoke(coerce.clj:51)
	at compojure.core$pre_init$fn__21382$fn__21385.invoke(core.clj:335)
	at compojure.core$wrap_route_middleware$fn__21313.invoke(core.clj:127)
	at compojure.core$wrap_route_info$fn__21318.invoke(core.clj:137)
	at compojure.core$wrap_route_matches$fn__21322.invoke(core.clj:146)
	at compojure.core$wrap_routes$fn__21392.invoke(core.clj:348)
	at compojure.api.routes.Route.invoke(routes.clj:74)
	at compojure.core$routing$fn__21337.invoke(core.clj:185)
	at clojure.core$some.invokeStatic(core.clj:2693)
	at clojure.core$some.invoke(core.clj:2684)
	at compojure.core$routing.invokeStatic(core.clj:185)
	at compojure.core$routing.doInvoke(core.clj:182)
	at clojure.lang.RestFn.applyTo(RestFn.java:139)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$apply.invoke(core.clj:652)
	at compojure.core$routes$fn__21341.invoke(core.clj:192)
	at compojure.core$routing$fn__21337.invoke(core.clj:185)
	at clojure.core$some.invokeStatic(core.clj:2693)
	at clojure.core$some.invoke(core.clj:2684)
	at compojure.core$routing.invokeStatic(core.clj:185)
	at compojure.core$routing.doInvoke(core.clj:182)
	at clojure.lang.RestFn.applyTo(RestFn.java:139)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$apply.invoke(core.clj:652)
	at compojure.core$routes$fn__21341.invoke(core.clj:192)
	at compojure.core$make_context$handler__21369.invoke(core.clj:285)
	at compojure.core$make_context$fn__21371.invoke(core.clj:293)
	at compojure.api.routes.Route.invoke(routes.clj:74)
	at compojure.api.core$handle$fn__24796.invoke(core.clj:8)
	at clojure.core$some.invokeStatic(core.clj:2693)
	at clojure.core$some.invoke(core.clj:2684)
	at compojure.api.core$handle.invokeStatic(core.clj:8)
	at compojure.api.core$handle.invoke(core.clj:7)
	at clojure.core$partial$fn__5561.invoke(core.clj:2616)
	at compojure.api.routes.Route.invoke(routes.clj:74)
	at compojure.api.core$handle$fn__24796.invoke(core.clj:8)
	at clojure.core$some.invokeStatic(core.clj:2693)
	at clojure.core$some.invoke(core.clj:2684)
	at compojure.api.core$handle.invokeStatic(core.clj:8)
	at compojure.api.core$handle.invoke(core.clj:7)
	at clojure.core$partial$fn__5561.invoke(core.clj:2616)
	at compojure.api.routes.Route.invoke(routes.clj:74)
	at compojure.core$routing$fn__21337.invoke(core.clj:185)
	at clojure.core$some.invokeStatic(core.clj:2693)
	at clojure.core$some.invoke(core.clj:2684)
	at compojure.core$routing.invokeStatic(core.clj:185)
	at compojure.core$routing.doInvoke(core.clj:182)
	at clojure.lang.RestFn.applyTo(RestFn.java:139)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$apply.invoke(core.clj:652)
	at compojure.core$routes$fn__21341.invoke(core.clj:192)
	at compojure.core$routing$fn__21337.invoke(core.clj:185)
	at clojure.core$some.invokeStatic(core.clj:2693)
	at clojure.core$some.invoke(core.clj:2684)
	at compojure.core$routing.invokeStatic(core.clj:185)
	at compojure.core$routing.doInvoke(core.clj:182)
	at clojure.lang.RestFn.applyTo(RestFn.java:139)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$apply.invoke(core.clj:652)
	at compojure.core$routes$fn__21341.invoke(core.clj:192)
	at compojure.core$make_context$handler__21369.invoke(core.clj:285)
	at compojure.core$make_context$fn__21371.invoke(core.clj:293)
	at compojure.api.routes.Route.invoke(routes.clj:74)
	at compojure.api.core$handle$fn__24796.invoke(core.clj:8)
	at clojure.core$some.invokeStatic(core.clj:2693)
	at clojure.core$some.invoke(core.clj:2684)
	at compojure.api.core$handle.invokeStatic(core.clj:8)
	at compojure.api.core$handle.invoke(core.clj:7)
	at clojure.core$partial$fn__5561.invoke(core.clj:2616)
	at compojure.api.routes.Route.invoke(routes.clj:74)
	at compojure.api.core$handle$fn__24796.invoke(core.clj:8)
	at clojure.core$some.invokeStatic(core.clj:2693)
	at clojure.core$some.invoke(core.clj:2684)
	at compojure.api.core$handle.invokeStatic(core.clj:8)
	at compojure.api.core$handle.invoke(core.clj:7)
	at clojure.core$partial$fn__5561.invoke(core.clj:2616)
	at compojure.api.routes.Route.invoke(routes.clj:74)
	at ctia.http.middleware.auth$wrap_authenticated$fn__24773.invoke(auth.clj:40)
	at compojure.api.routes.Route.invoke(routes.clj:74)
	at compojure.core$routing$fn__21337.invoke(core.clj:185)
	at clojure.core$some.invokeStatic(core.clj:2693)
	at clojure.core$some.invoke(core.clj:2684)
	at compojure.core$routing.invokeStatic(core.clj:185)
	at compojure.core$routing.doInvoke(core.clj:182)
	at clojure.lang.RestFn.applyTo(RestFn.java:139)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$apply.invoke(core.clj:652)
	at compojure.core$routes$fn__21341.invoke(core.clj:192)
	at compojure.core$routing$fn__21337.invoke(core.clj:185)
	at clojure.core$some.invokeStatic(core.clj:2693)
	at clojure.core$some.invoke(core.clj:2684)
	at compojure.core$routing.invokeStatic(core.clj:185)
	at compojure.core$routing.doInvoke(core.clj:182)
	at clojure.lang.RestFn.applyTo(RestFn.java:139)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$apply.invoke(core.clj:652)
	at compojure.core$routes$fn__21341.invoke(core.clj:192)
	at compojure.core$make_context$handler__21369.invoke(core.clj:285)
	at compojure.core$make_context$fn__21371.invoke(core.clj:293)
	at compojure.api.routes.Route.invoke(routes.clj:74)
	at compojure.api.core$handle$fn__24796.invoke(core.clj:8)
	at clojure.core$some.invokeStatic(core.clj:2693)
	at clojure.core$some.invoke(core.clj:2684)
	at compojure.api.core$handle.invokeStatic(core.clj:8)
	at compojure.api.core$handle.invoke(core.clj:7)
	at clojure.core$partial$fn__5561.invoke(core.clj:2616)
	at compojure.api.routes.Route.invoke(routes.clj:74)
	at metrics.ring.instrument$handle_request$fn__60637.invoke(instrument.clj:65)
	at metrics.ring.instrument.proxy$java.lang.Object$Callable$7da976d4.call(Unknown Source)
	at com.codahale.metrics.Timer.time(Timer.java:101)
	at metrics.ring.instrument$handle_request.invokeStatic(instrument.clj:64)
	at metrics.ring.instrument$handle_request.invoke(instrument.clj:54)
	at metrics.ring.instrument$instrument$fn__60645.invoke(instrument.clj:91)
	at clj_momo.ring.middleware.metrics$gen_metrics_for$fn__60707$fn__60708.invoke(metrics.clj:59)
	at clj_momo.ring.middleware.metrics.proxy$java.lang.Object$Callable$7da976d4.call(Unknown Source)
	at com.codahale.metrics.Timer.time(Timer.java:101)
	at clj_momo.ring.middleware.metrics$gen_metrics_for$fn__60707.invoke(metrics.clj:59)
	at ctia.http.middleware.version$wrap_version$fn__62385.invoke(version.clj:9)
	at ctia.http.middleware.cache_control$wrap_cache_control$fn__62367.invoke(cache_control.clj:29)
	at ring.middleware.not_modified$wrap_not_modified$fn__24852.invoke(not_modified.clj:53)
	at compojure.api.routes.Route.invoke(routes.clj:74)
	at compojure.api.core$handle$fn__24796.invoke(core.clj:8)
	at clojure.core$some.invokeStatic(core.clj:2693)
	at clojure.core$some.invoke(core.clj:2684)
	at compojure.api.core$handle.invokeStatic(core.clj:8)
	at compojure.api.core$handle.invoke(core.clj:7)
	at clojure.core$partial$fn__5561.invoke(core.clj:2616)
	at compojure.api.routes.Route.invoke(routes.clj:74)
	at ring.swagger.middleware$wrap_swagger_data$fn__24301.invoke(middleware.clj:35)
	at ring.middleware.http_response$wrap_http_response$fn__24160.invoke(http_response.clj:19)
	at ring.swagger.middleware$wrap_swagger_data$fn__24301.invoke(middleware.clj:35)
	at compojure.api.middleware$wrap_options$fn__24362.invoke(middleware.clj:74)
	at ring.middleware.format_params$wrap_format_params$fn__23301.invoke(format_params.clj:117)
	at ring.middleware.format_params$wrap_format_params$fn__23301.invoke(format_params.clj:119)
	at ring.middleware.format_params$wrap_format_params$fn__23301.invoke(format_params.clj:119)
	at ring.middleware.format_params$wrap_format_params$fn__23301.invoke(format_params.clj:119)
	at ring.middleware.format_params$wrap_format_params$fn__23301.invoke(format_params.clj:119)
	at compojure.api.middleware$wrap_exceptions$fn__24352.invoke(middleware.clj:43)
	at ring.middleware.format_response$wrap_format_response$fn__24062.invoke(format_response.clj:194)
	at ring.middleware.keyword_params$wrap_keyword_params$fn__24194.invoke(keyword_params.clj:36)
	at ring.middleware.nested_params$wrap_nested_params$fn__24244.invoke(nested_params.clj:89)
	at ring.middleware.params$wrap_params$fn__24292.invoke(params.clj:67)
	at compojure.api.middleware$wrap_options$fn__24362.invoke(middleware.clj:74)
	at compojure.api.routes.Route.invoke(routes.clj:74)
	at ctia.http.middleware.auth$testable_wrap_authentication$fn__24768.invoke(auth.clj:22)
	at ctia.auth.jwt$wrap_jwt_to_ctia_auth$fn__60603.invoke(jwt.clj:126)
	at ring_jwt_middleware.core$wrap_jwt_auth_fn$fn__60501$fn__60502.invoke(core.clj:268)
	at ring.middleware.cors$handle_cors.invokeStatic(cors.clj:161)
	at ring.middleware.cors$handle_cors.invoke(cors.clj:153)
	at ring.middleware.cors$wrap_cors$fn__62922.invoke(cors.clj:178)
	at ring.middleware.params$wrap_params$fn__24292.invoke(params.clj:67)
	at ring.adapter.jetty$proxy_handler$fn__62839.invoke(jetty.clj:25)
	at ring.adapter.jetty.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:258)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by gbuisson** [comment]
I reproduced the issue trying to issue a patch operation on a non existing casebook: 

```java
lein test ctia.entity.casebook-test
2018-11-16 14:32:38,322 ERROR (qtp224909122-33 - /ctia/casebook/casebook-849aaa02-6eff-4150-947b-4cda746ed81b42/observables) [ctia.http.exceptions] - Response validation failed: schema.utils.ValidationError@eb4d904 - Meta: #schema.utils.ErrorContainer{:error (not (map? nil)), :type :compojure.api.exception/response-validation, :response {:status 200, :headers {}, :body nil}}
clojure.lang.ExceptionInfo: Response validation failed: schema.utils.ValidationError@eb4d904 schema.utils.ErrorContainer@c164432f
```

**Comment by hshahman** [comment]
Verified in rel-v1.14
