### ISSUE TITLE
Getting 401 when sending query to "/delete/event/{id}" endpoint in Private CTIA

### ISSUE THREAD

**Issue by hshahman** [threatgrid/ctia#801]
Env: TEST

I'm using a JWT, which has a full access (r/w) to Private CTIA since it has both  `casebook`, `private-intel` scopes. When sending a query to the delete endpoint of events, it returns a 401 error.

CURL: 
```
curl -X DELETE --header 'Accept: application/json' --header 'Authorization: Bearer <JWT_TOKEN>' 'https://private.intel.test.iroh.site/ctia/event/https%3A%2F%2Fprivate.intel.test.iroh.site%3A443%2Fctia%2Fevent%2Fevent-65371c51-ff9f-40b7-a6e7-2be4977d719c'
```

Kibana: 
```
2019-02-26 18:51:14,384 INFO (qtp1640621638-42 - /ctia/event/https%3A%2F%2Fprivate.intel.test.iroh.site%3A443%2Fctia%2Fevent%2Fevent-65371c51-ff9f-40b7-a6e7-2be4977d719c) [ctia.http.exceptions] - You are not allowed to read this document - Meta: {:type :access-control-error}
clojure.lang.ExceptionInfo: You are not allowed to read this document {:type :access-control-error}
	at clojure.core$ex_info.invokeStatic(core.clj:4739)
	at clojure.core$ex_info.invoke(core.clj:4739)
	at ctia.stores.es.crud$handle_read$fn39772__39785$fn__39786.invoke(crud.clj:149)
	at ctia.stores.es.crud$handle_read$fn39772__39785.invoke(crud.clj:137)
	at clojure.lang.AFn.applyToHelper(AFn.java:165)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.lang.AFunction$1.doInvoke(AFunction.java:29)
	at clojure.lang.RestFn.invoke(RestFn.java:457)
	at ctia.entity.event.store.EventStore.read_record(store.clj:15)
	at ctia.store$fn__17636$G__17592__17641.invoke(store.clj:5)
	at ctia.store$fn__17636$G__17591__17647.invoke(store.clj:5)
	at clojure.lang.AFn.applyToHelper(AFn.java:165)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$apply.invoke(core.clj:652)
	at ctia.store$read_store.invokeStatic(store.clj:60)
	at ctia.store$read_store.doInvoke(store.clj:59)
	at clojure.lang.RestFn.invoke(RestFn.java:490)
	at ctia.http.routes.crud$entity_crud_routes$fn__37826$fn__37829.invoke(crud.clj:214)
	at ctia.flows.crud$delete_flow.invokeStatic(crud.clj:506)
	at ctia.flows.crud$delete_flow.doInvoke(crud.clj:493)
	at clojure.lang.RestFn.invoke(RestFn.java:1096)
	at ctia.http.routes.crud$entity_crud_routes$fn__37826.invoke(crud.clj:213)
	at compojure.core$wrap_response$fn__21181.invoke(core.clj:158)
	at compojure.core$wrap_route_middleware$fn__21165.invoke(core.clj:128)
	at compojure.core$wrap_route_info$fn__21170.invoke(core.clj:137)
	at compojure.core$wrap_route_matches$fn__21174.invoke(core.clj:146)
	at compojure.api.routes.Route.invoke(routes.clj:74)
	at compojure.api.core$handle$fn__24648.invoke(core.clj:8)
	at clojure.core$some.invokeStatic(core.clj:2693)
	at clojure.core$some.invoke(core.clj:2684)
	at compojure.api.core$handle.invokeStatic(core.clj:8)
	at compojure.api.core$handle.invoke(core.clj:7)
	at clojure.core$partial$fn__5561.invoke(core.clj:2616)
	at compojure.api.routes.Route.invoke(routes.clj:74)
	at compojure.api.core$handle$fn__24648.invoke(core.clj:8)
	at clojure.core$some.invokeStatic(core.clj:2693)
	at clojure.core$some.invoke(core.clj:2684)
	at compojure.api.core$handle.invokeStatic(core.clj:8)
	at compojure.api.core$handle.invoke(core.clj:7)
	at clojure.core$partial$fn__5561.invoke(core.clj:2616)
	at compojure.api.routes.Route.invoke(routes.clj:74)
	at compojure.core$routing$fn__21189.invoke(core.clj:185)
	at clojure.core$some.invokeStatic(core.clj:2693)
	at clojure.core$some.invoke(core.clj:2684)
	at compojure.core$routing.invokeStatic(core.clj:185)
	at compojure.core$routing.doInvoke(core.clj:182)
	at clojure.lang.RestFn.applyTo(RestFn.java:139)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$apply.invoke(core.clj:652)
	at compojure.core$routes$fn__21193.invoke(core.clj:192)
	at compojure.core$routing$fn__21189.invoke(core.clj:185)
	at clojure.core$some.invokeStatic(core.clj:2693)
	at clojure.core$some.invoke(core.clj:2684)
	at compojure.core$routing.invokeStatic(core.clj:185)
	at compojure.core$routing.doInvoke(core.clj:182)
	at clojure.lang.RestFn.applyTo(RestFn.java:139)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$apply.invoke(core.clj:652)
	at compojure.core$routes$fn__21193.invoke(core.clj:192)
	at compojure.core$make_context$handler__21221.invoke(core.clj:285)
	at compojure.core$make_context$fn__21223.invoke(core.clj:293)
	at compojure.api.routes.Route.invoke(routes.clj:74)
	at compojure.api.core$handle$fn__24648.invoke(core.clj:8)
	at clojure.core$some.invokeStatic(core.clj:2693)
	at clojure.core$some.invoke(core.clj:2684)
	at compojure.api.core$handle.invokeStatic(core.clj:8)
	at compojure.api.core$handle.invoke(core.clj:7)
	at clojure.core$partial$fn__5561.invoke(core.clj:2616)
	at compojure.api.routes.Route.invoke(routes.clj:74)
	at compojure.api.core$handle$fn__24648.invoke(core.clj:8)
	at clojure.core$some.invokeStatic(core.clj:2693)
	at clojure.core$some.invoke(core.clj:2684)
	at compojure.api.core$handle.invokeStatic(core.clj:8)
	at compojure.api.core$handle.invoke(core.clj:7)
	at clojure.core$partial$fn__5561.invoke(core.clj:2616)
	at compojure.api.routes.Route.invoke(routes.clj:74)
	at ctia.http.middleware.auth$wrap_authenticated$fn__24625.invoke(auth.clj:40)
	at compojure.api.routes.Route.invoke(routes.clj:74)
	at compojure.core$routing$fn__21189.invoke(core.clj:185)
	at clojure.core$some.invokeStatic(core.clj:2693)
	at clojure.core$some.invoke(core.clj:2684)
	at compojure.core$routing.invokeStatic(core.clj:185)
	at compojure.core$routing.doInvoke(core.clj:182)
	at clojure.lang.RestFn.applyTo(RestFn.java:139)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$apply.invoke(core.clj:652)
	at compojure.core$routes$fn__21193.invoke(core.clj:192)
	at compojure.core$routing$fn__21189.invoke(core.clj:185)
	at clojure.core$some.invokeStatic(core.clj:2693)
	at clojure.core$some.invoke(core.clj:2684)
	at compojure.core$routing.invokeStatic(core.clj:185)
	at compojure.core$routing.doInvoke(core.clj:182)
	at clojure.lang.RestFn.applyTo(RestFn.java:139)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$apply.invoke(core.clj:652)
	at compojure.core$routes$fn__21193.invoke(core.clj:192)
	at compojure.core$make_context$handler__21221.invoke(core.clj:285)
	at compojure.core$make_context$fn__21223.invoke(core.clj:293)
	at compojure.api.routes.Route.invoke(routes.clj:74)
	at compojure.api.core$handle$fn__24648.invoke(core.clj:8)
	at clojure.core$some.invokeStatic(core.clj:2693)
	at clojure.core$some.invoke(core.clj:2684)
	at compojure.api.core$handle.invokeStatic(core.clj:8)
	at compojure.api.core$handle.invoke(core.clj:7)
	at clojure.core$partial$fn__5561.invoke(core.clj:2616)
	at compojure.api.routes.Route.invoke(routes.clj:74)
	at metrics.ring.instrument$handle_request$fn__53965.invoke(instrument.clj:65)
	at metrics.ring.instrument.proxy$java.lang.Object$Callable$7da976d4.call(Unknown Source)
	at com.codahale.metrics.Timer.time(Timer.java:101)
	at metrics.ring.instrument$handle_request.invokeStatic(instrument.clj:64)
	at metrics.ring.instrument$handle_request.invoke(instrument.clj:54)
	at metrics.ring.instrument$instrument$fn__53973.invoke(instrument.clj:91)
	at clj_momo.ring.middleware.metrics$gen_metrics_for$fn__54035$fn__54036.invoke(metrics.clj:59)
	at clj_momo.ring.middleware.metrics.proxy$java.lang.Object$Callable$7da976d4.call(Unknown Source)
	at com.codahale.metrics.Timer.time(Timer.java:101)
	at clj_momo.ring.middleware.metrics$gen_metrics_for$fn__54035.invoke(metrics.clj:59)
	at ctia.http.middleware.version$wrap_version$fn__55715.invoke(version.clj:9)
	at ctia.http.middleware.cache_control$wrap_cache_control$fn__55697.invoke(cache_control.clj:29)
	at ring.middleware.not_modified$wrap_not_modified$fn__24704.invoke(not_modified.clj:53)
	at compojure.api.routes.Route.invoke(routes.clj:74)
	at compojure.api.core$handle$fn__24648.invoke(core.clj:8)
	at clojure.core$some.invokeStatic(core.clj:2693)
	at clojure.core$some.invoke(core.clj:2684)
	at compojure.api.core$handle.invokeStatic(core.clj:8)
	at compojure.api.core$handle.invoke(core.clj:7)
	at clojure.core$partial$fn__5561.invoke(core.clj:2616)
	at compojure.api.routes.Route.invoke(routes.clj:74)
	at ring.swagger.middleware$wrap_swagger_data$fn__24153.invoke(middleware.clj:35)
	at ring.middleware.http_response$wrap_http_response$fn__24012.invoke(http_response.clj:19)
	at ring.swagger.middleware$wrap_swagger_data$fn__24153.invoke(middleware.clj:35)
	at compojure.api.middleware$wrap_options$fn__24214.invoke(middleware.clj:74)
	at ring.middleware.format_params$wrap_format_params$fn__23153.invoke(format_params.clj:119)
	at ring.middleware.format_params$wrap_format_params$fn__23153.invoke(format_params.clj:119)
	at ring.middleware.format_params$wrap_format_params$fn__23153.invoke(format_params.clj:119)
	at ring.middleware.format_params$wrap_format_params$fn__23153.invoke(format_params.clj:119)
	at ring.middleware.format_params$wrap_format_params$fn__23153.invoke(format_params.clj:119)
	at compojure.api.middleware$wrap_exceptions$fn__24204.invoke(middleware.clj:43)
	at ring.middleware.format_response$wrap_format_response$fn__23914.invoke(format_response.clj:194)
	at ring.middleware.keyword_params$wrap_keyword_params$fn__24046.invoke(keyword_params.clj:36)
	at ring.middleware.nested_params$wrap_nested_params$fn__24096.invoke(nested_params.clj:89)
	at ring.middleware.params$wrap_params$fn__24144.invoke(params.clj:67)
	at compojure.api.middleware$wrap_options$fn__24214.invoke(middleware.clj:74)
	at compojure.api.routes.Route.invoke(routes.clj:74)
	at ctia.http.middleware.auth$testable_wrap_authentication$fn__24620.invoke(auth.clj:22)
	at ctia.auth.jwt$wrap_jwt_to_ctia_auth$fn__53931.invoke(jwt.clj:123)
	at ring_jwt_middleware.core$wrap_jwt_auth_fn$fn__53829$fn__53830.invoke(core.clj:268)
	at ring.middleware.cors$handle_cors.invokeStatic(cors.clj:161)
	at ring.middleware.cors$handle_cors.invoke(cors.clj:153)
	at ring.middleware.cors$wrap_cors$fn__56276.invoke(cors.clj:178)
	at ring.middleware.params$wrap_params$fn__24144.invoke(params.clj:67)
	at ring.adapter.jetty$proxy_handler$fn__56193.invoke(jetty.clj:25)
	at ring.adapter.jetty.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:258)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by hshahman** [comment]
Note: QA can verify using `C509009`
